bitcoin-dot-org/Bitcoin.org

_plugins/releases.rb
en/version-history.html

[This comment](https://github.com/bitcoin/bitcoin.org/pull/710#issuecomment-70415594) outlined that releases numbers might not always be in chronological order (e.g. 0.9.5 to be released after 0.10.0) which would affect the version served on the download page as well as the order on the version history page.
This pull request should prevent this issue as long as version numbers do not use more decimal places or digits than this example "000.000.000.000.000" .
In the absence of critical feedback, this pull request will be merged on January 21th.

Order release history and set latest version using versions number instead of releases date

---

_autocrossref.yaml
_includes/ref_block_chain.md
_includes/references.md

Preview: http://dg2.dtrt.org/en/developer-reference#block-versions
Briefly mention upcoming v3 blocks and BIP66 (strict DER).  We don't currently have any docs about creating signatures, so I don't think there's anything else we need to change.
Note: the link to BIP66 is broken because Greg Maxwell just assigned the BIP number. I won't merge this request until the link works.

Dev Docs: Mention Upcoming v3 Blocks/BIP66

---

_templates/resources.html

"[France Bitcoin](http://francebitcoin.com/)" should be moved from Useful places to the News section, since it's only a news website.
Edit : Maybe it should even be deleted as the last post is almost 1 year old...

Remove "France Bitcoin" from resources page

---

_translations/fr.yml

There is a small error in the French translation of the [Vocabulary](https://bitcoin.org/fr/vocabulaire#bit) page:
"**Bit** is a common unit" is translated into French as "**Bitcoin** est une unité courante"

Small error in the French translation (Bitcoin instead of Bit)

---

_templates/resources.html
_translations/en.yml

As suggested in #734
In the absence of critical feedback, this pull request will be merged on February 8th.

Add links to givebtc.org

---

README.md

Preview: https://github.com/harding/bitcoin.org/tree/readme-update#how-to-participate
This suggests specific tasks for new volunteers and links directly to relevant pages or README sections.
We also advise submitters of new wallets to read the requirements list.
(In the absence of critical feedback, this pull will be merged in 72 hours, around 22:00 UTC Thursday.)

Site Docs: Stregthen Appeal For Volunteers In README

---

_layouts/base.html
_templates/download.html
js/base.js
js/main.js

I have been working with the help of @harding on allowing the binaries and download page to be closely monitored by scripts. One remaining issue I had was the number of alerts triggered by unimportant changes in the javascript code. This pull request aims to reduce this useless noise by two means.
By only loading the few necessary javascript functions required for this page to work.
By not changing the javascript code on the page on each release.
I'll be happy to wait and rebase this pull request if needed given that the download page is receiving a lot of changes recently.
Edit:
Live preview: http://bitcointest1.us.to/en/download
Result diff: http://bitcointest1.us.to/diff.html

Reduce future changes to the javascript code of the download page

---

_templates/choose-your-wallet.html

This reverts commit bf452cdc171eeddf4015034297bb59c907dd04eb.
According to @apetersson in merged pull #630, Mycelium now supports using Tor, so this restores that part of their score.
In the absence of critical feedback, I'll verify this and merge it in about 72 hours (17:00 UTC Saturday).

Wallets: Revert "Drop good tor privacy score for mycelium"

---

_templates/bitcoin-for-developers.html

I find misleading that the [Bitcoin for Developers](https://bitcoin.org/en/bitcoin-for-developers) page has the same "Get started with Bitcoin" button as the other pages but with a different link (english only, even if the button is translated).
I propose:
1. Restore the same link for the button as the other pages ([Getting started](https://bitcoin.org/en/getting-started)).
2. Add a Developer Documentation link without translating: I think this is not a problem / more indicative because the documentation is English only.

Bitcoin for Developers: Change links

---

.travis.yml
README.md
_config.yml

This pull adds a control file for automatically test building the site in Travis CI.  The pull also adds documentation and makes one minor change to the _config.yml file to prevent conflicting with Travis.
In addition to merging this pull, a Travis webhook needs to be installed.  One of the core devs has already given Travis permission to toggle that hook, and I have sufficient permissions to tell Travis to enable it---so if this PR is ACKed, I will enable it before merging.
Once everything is enabled, all bitcoin/bitcoin.org branches will be test built and all PRs against bitcoin/bitcoin.org branches will also be test built.  A message will be left on the PRs indicating whether or not they passed the test build and an icon at the top of our README.md will indicate the status of the …

Backend: Test That Site Builds With Travis CI

---

_less/screen.less

Just a very small change, I've reduced the margin on the Getting started page. This make the page a bit denser, useful for mobile and small screens.

Small change: make Getting started more dense

---

_layouts/base.html

This fixes #808 for some reason, must be a bug in chrome.. Tested the change on safari and firefox and then still render it fine. I'm a bit frustrated that I have no clue why this fixes the issue in chrome :)
@saivann

Fixes the position of the nav icon when resizeing the window on Chrome

---

_less/screen.less

https://bitcoin.org/en/developer-documentation the links with icons looks broken on tablets/large phones.

Stylefix on dev docs page

---

_layouts/base.html
_templates/faq.html
_templates/vocabulary.html
en/developer-examples.md
en/developer-guide.md
en/developer-reference.md
en/full-node.md
js/base.js
js/main.js

This pull calls a Javascript function to display a hyperlinked icon whenever a Javascript-enabled user hovers on any subhead on the site that has an anchor set.  Combined with PR #813, it makes it easy for users to link to any section within the site.
This pull request is being added to the bitcoin-core-0.10.1 branch because updating the Javascript will trigger an alert to people monitoring the page.  Since that alert will be triggered when 0.10.1 is released, this will avoid an unnecessary extra alert.
Live preview of this PR plus PR #813 merged together: http://dg1.dtrt.org/en/bitcoin-for-individuals
Screenshots of the anchor link icon in different layouts:
Note: this branch will fail Travis CI because its based on the 0.10.1 branch that itself fails until 0.10.1 final is uploaded to …

Layout: Add anchor link affordance to all pages

---

_layouts/base.html
_less/screen.less
_translations/ar.yml
_translations/bg.yml
_translations/da.yml
_translations/de.yml
_translations/el.yml
_translations/en.yml
_translations/es.yml
_translations/fa.yml
_translations/fr.yml
_translations/hi.yml
_translations/hu.yml
_translations/id.yml
_translations/it.yml
_translations/ja.yml
_translations/ko.yml
_translations/nl.yml
_translations/pl.yml
_translations/pt_BR.yml
_translations/ro.yml
_translations/ru.yml
_translations/sl.yml
_translations/sv.yml
_translations/tr.yml
_translations/uk.yml
_translations/zh_CN.yml
_translations/zh_TW.yml

Live preview: http://bitcointest1.us.to/
I remember reading comments saying the "Development" page was buried and hard to find, and the current guide to run a full node isn't visible in the menus either. I feel like these two would find their right audience and get more visibility by becoming a submenu of the "Participate" menu entry.

Expend the "Participate" menu entry

---

_build/update_site.sh
_build/update_txpreview.sh

The subshell used in the script to prevent it from building if another concurrent build starts had the unintended consequence of creating an endless loop when the build script fails.
This pull request allows the script to terminate correctly.
Additionally this pull request enables the quick Makefile tests to catch issues in order to prevent the server to push any broken update (as we've already planned to do, it currently works fine on the build machine according to my testing).

Fix endless loop bug in build scripts

---

_autocrossref.yaml
_includes/example_testing.md
_includes/example_transactions.md
_includes/helpers/summaries.md
_includes/ref/bitcoin-core/rpcs/quick-ref.md
_includes/ref/bitcoin-core/rpcs/rpcs/generate.md
_includes/ref/bitcoin-core/rpcs/rpcs/setgenerate.md
_includes/references.md
en/developer-reference.md

Preview: http://dg2.dtrt.org/en/developer-reference#generate
* Add a new section to the RPC docs describing the new `generate` RPC
* Mention that the `setgenerate` special mode in regtest has been removed in master
* Update raw transaction tutorial on the Examples doc to describe `generate` in addition to `setgenerate`
The need to update the docs was [mentioned on bitcoin-development](http://www.mail-archive.com/bitcoin-development@lists.sourceforge.net/msg07369.html) by @sipa (thanks!)

Dev Docs: Update For New 'generate' RPC

---

Makefile
README.md
_layouts/base.html
_releases/0.10.1.md
_templates/faq.html
_templates/vocabulary.html
en/full-node.md
js/base.js
js/main.js

Preview: http://dg4.dtrt.org/en/download and http://dg4.dtrt.org/en/release/v0.10.1
This updates the download links to point to 0.10.1 and adds the 0.10.1RC3 release notes to the site.  I'll keep it updated througout the RC cycle, but it can be merged by anyone with commit access once 0.10.1 final is released (see TODO lists below).
CC: @laanwj
Essential TODO:
Optional TODO (may be done in commits after merge):
Expected URLs for the binaries and torrent are:
/bin/bitcoin-core-0.10.1/bitcoin-0.10.1-linux32.tar.gz
/bin/bitcoin-core-0.10.1/bitcoin-0.10.1-linux64.tar.gz
/bin/bitcoin-core-0.10.1/bitcoin-0.10.1-osx64.tar.gz
/bin/bitcoin-core-0.10.1/bitcoin-0.10.1-osx.dmg
/bin/bitcoin-core-0.10.1/bitcoin-0.10.1.tar.gz
/bin/bitcoin-core-0.10.1/bitcoin-0.10.1.torrent …

Releases: Add Bitcoin Core 0.10.1

---

_templates/about-us.html
_translations/en.yml

* Add Craig Watkins (wallet reviews) @crwatkins
* Remove long-idle contributors
* Update all personal links to point to GitHub, which allows contributors to set email/web addresses
Looks like this:

About Us: Minor Updates

---

_less/screen.less
_plugins/events.rb
_templates/events.html
js/events.js

When monitoring sensitive changes on the website, regular script changes on all event pages are generating unhelpful non-descriptive noise, which might grab my attention away from real suspicious script changes.
This change renders events links and data directly on the page (inside an hidden DIV) and lets the script grab required data from there instead.

Separate event script from event data

---

Makefile

This bug was preventing translation live previews to be generated due to blank lines in the urls of some recent translations.
For instance, current unreviewed Spanish translations generate a "_site/es/documento de bitcoin.html" page. With the current Makefile, xargs would search for (and fail to find) "_site/es/documento", "de", and "bitcoin.html".
Such troublesome urls are prevented on the live website using the check-for-non-ascii-urls rules in the Makefile. However, live previews are meant to ignore such mistakes (using only "make build") so all working pages can be built and previewed without interruption.

Support blank spaces in file names when generating sha256sums.txt

---

Gemfile
Gemfile.lock

Updates to a newer version of Kramdown, the library used to convert Markdown to HTML.  A diff of the generated website using the previous version to the new version is available [here](http://dtrt.org/diff.html).  There are only two changes that I see:
1. Automatically-generated table of contents for the various dev docs now have an id attribute assigned to each list item.  Every id starts with `markdown-toc-` so I doubt there are any conflicts with previous ids and I don't see any issues.
2. In plain-text paragraphs and list items converted to HTML by Kramdown, trailing whitespace is now removed. I confirmed this does not apply to anything inside pre tags. I also confirmed that it only applies to trailing whitespace.
Not visible is that the old version of Kramdown has problems with HTML …

Backend: Update Kramdown Version

---

_plugins/githubify.rb
_releases/0.10.0.md
_releases/0.10.1.md
_releases/0.10.2.md

Starting with the 0.10.x series, @laanwj began adding commit ids to the release notes.  In the 0.11.0 notes, he also adds pull request numbers.
This PR adds a plugin that automatically converts those ids and PR#s into links.  Previews:
* http://dg1.dtrt.org/en/release/v0.10.0
* http://dg1.dtrt.org/en/release/v0.10.1
* http://dg1.dtrt.org/en/release/v0.10.2
HTML diff (I don't see any false positive matches or other unwanted changes): http://dg1.dtrt.org/diff.html
I already have the initial 0.11.0 release commit based on top of this, so a preview for that will be available as soon as I finish testing it and writing the PR notes.

New Plugin: Githubify Bitcoin Core Release Notes

---

_posts/2015-06-16-hard-fork-policy.md

This blog post introduces a new policy for Bitcoin.org regarding contentious hard forks:
> Bitcoin.org will not promote software or services that will leave the previous consensus because of a contentious hard fork attempt.
Full explanation can be found in the blog post itself using the GitHub diff on the screenshot preview below.
This statement, or earlier revisions of it, has been reviewed by the following persons:
* @theymos (Bitcoin.org domain co-owner)
* Cobra (Bitcoin.org domain co-owner)
* @saivann (Bitcoin.org site co-maintainer)
* @harding (Bitcoin.org site co-maintainer)
We also feel that this statement reflects the published sentiments of many of Bitcoin.org's active reviewers, and we invite them to individually ACK this PR if that is the case.  If a sufficient number ACK this …

Blog: Bitcoin.org Position On Hard Forks

---

_build/update_site.sh

This pull request adds support for gzip compression in order to increase performance and reduce load on the server (thanks to @louisjc and @harding for the idea on issue #916).
This single line change allows the build script to generate a .gz copy of all files for which compression offers a measurable improvement. This is done right after the website has successfully built, and before transferring files to the live server.
I have tested the build script and nginx locally with the following configuration and everything seemed to work as expected. Only compressed files are sent using gzip as the Content-Encoding header. The website also remains compatible with IE6 as expected.
~~~
gzip_static on;
gzip_disable "msie6";
~~~
@harding sha256sums.txt is already generated before files are …

Enable gzip compression

---

README.md

The Bitcoin.org readme covers the basics of opening a PR, but it doesn't document any sort of everyday workflow for regular contributors.  I think documenting that directly in the readme might confuse newbies, so I documented it elsewhere and asked a couple contributors to review it.
They thought it was useful (thanks!), so this PR adds a link to it from the readme.

Site Readme: Link To More Advanced Workflow Doc

---

_data/glossary/en/sighash-anyonecanpay.yaml
_data/glossary/en/sighash-single.yaml
_includes/guide_transactions.md

First, there was a mis-directed link that was going to the SIGHASH_NONE definition page.
Second, the definitions for SIGHASH_SINGLE didn't seem to be consistent with the current code. The definitions at https://en.bitcoin.it/wiki/OP_CHECKSIG seem much closer. The code I'm looking at is https://github.com/bitcoin/bitcoin/blob/bc60b2b4b401f0adff5b8b9678903ff8feb5867b/src/script/interpreter.cpp#L-1024-1101
Hopefully, these definitions are closer to how it actually works.

DevDocs: update a mis-directed link and clarify SIGHASH_SINGLE definitions

---

_layouts/base.html
_less/ie8.less
_less/screen.less
js/main.js

There is currently 4 different javascript functions duplicating code for doing mostly the same thing; animating lists or boxes as they expand on user demand.
This pull request makes some optimizations to simplify and shorten the code, by adopting better practices such as moving styles to CSS stylesheets and using a single function to do the animation.
At the same time, some big blocks of related CSS code used only for IE8's compatibility are moved into a separate file to reduce the load for most browsers and simplify compatibility maintenance.
I have tested the changes with IE8-9-10 and various OP, CH, SA, FF versions.
Live preview:
http://bitcointest1.us.to/en/press
http://bitcointest1.us.to/en/secure-your-wallet
http://bitcointest1.us.to/en/choose-your-wallet …

Simplify javascript code for expanding lists and blocks

---

_alerts/2015-07-04-spv-mining.html

Previews:
- http://dg0.dtrt.org/  (main page, alerts banner)
- http://dg0.dtrt.org/en/alert/2015-07-04-spv-mining (message first draft)
I'll merge this version as soon as it gets an ack from someone knowledgable about the situation, and then begin working on a longer and more detailed version.

Alerts: first version of invalid v3 blocks

---

_layouts/alert.html
_less/screen.less

Alert pages look like typical blog posts, not a PSA. Just adding one icon to the layout seems enough to fix that. Please feel free to merge at any moment or ignore if you feel it's unimportant.
Edit: Travis fail due to broken HTML in spv-mining not related to this PR.

Add warning icon to alert pages

---

_alerts/2015-07-04-spv-mining.html

This adds more details to the current alert message.  With F2Pool now fully validating, I've also reduced the number of recommended extra confrimations to wait from 30 to 15.  According to @gmaxwell's online version of the [fork probability calculator](https://people.xiph.org/~greg/attack_success.html), 15 confirmations on the longest chain from 25% of hash rate has a probability of 0.01%.
Preview: http://dg0.dtrt.org/en/alert/2015-07-04-spv-mining
CC: @petertodd @luke-jr

Alerts: SPV Mining more details

---

Makefile
_build/update_site.sh

This change brings significant performance improvement for the build process, as the build script otherwise deletes ./vendor, which forces bundler to reinstall every dependency from scratch on every build, which then delays the build for approximately 3 minutes.
It also seems to me that downloading and installing dependencies on every build exposes us to some more third party risk for no reason.
Git clean man file for the -x option:
https://git-scm.com/docs/git-clean

Avoid reinstalling dependencies with bundler on every build

---

_layouts/alert.html
_layouts/post.html
_less/screen.less
_plugins/alerts.rb
en/alerts.html
en/blog.html

~~@harding @btcdrak Would just adding the RSS icon into individual alerts would be good enough for now? Please feel free to merge this pull request at any time.~~
This pull request adds RSS icons and other features from the blog post layout.
Live preview:
http://bitcointest4.us.to/en/alerts
http://bitcointest4.us.to/en/alert/2015-07-04-spv-mining

Add more explicit RSS feed and other features from the blog layout to alerts

---

_build/update_site.sh
_build/update_txpreview.sh

Fixes issue (bug) #941 
While installing rvm as root (which is a pain) for a test environment, I realized what the problem with the current script was:
- `kill 0` kills all process in the current process group.  That includes *children* of the current shell, but not the shell itself (which has the pgid of its parent shell).
- By sourcing `rvm.sh` we were including the `rvm` shell function into the shell.  Unlike commands such as git, rsync, etc..., `rvm` wasn't a child process.
- So, when `kill 0` was run, it had no effect on the `rvm` function.
The solution was easy: push the sourcing of the `rvm.sh` function down a level into the build process sub-shell.
This PR has been implemented and well tested on the build server (and implemented and lightly tested on the translation preview …

Build: Push Function Include Down Into Sub-Shell

---

Makefile

While testing an update to the build system, I needed this for easily tracking which of my automated local test builds were successful.  However, I think it could also be useful for easily tracking what commit the site is on, so I'm submitting it as a separate PR.  Here's what the command outputs on current HEAD:
63361be Merge branch 'buildvendor'
I'd like to merge this later today; if anyone thinks this single line needs more review, please say so.
Once we upgrade to >= Jekyll 2.0, I think it might be worth trying https://github.com/ivantsepp/jekyll-git_metadata to add the current commit to templates, kind of like how Reddit has its current commit id and render date at the bottom right of every page.

(Trivial) Build: Put Current Git Commit ID On Site

---

_alerts/2015-07-04-spv-mining.html

Preview: http://dg0.dtrt.org/en/alert/2015-07-04-spv-mining
- Add bolded notice to top telling people the event is on going.  Some people on Reddit think it was a one-time fork.
- Link Electrum users [here](https://en.bitcoin.it/wiki/July_2015_Forks#Electrum) for help finding a Bitcoin Core 0.10.x-powered server.
- Add a table of forks related to SPV mining.  Link to a list of invalid block hashes.
- Remove hopeful note that miners were enabling full validation.  This appears not to be the case. :-(
- Add an update mentioning the July 5th fork
Also, used a hack to enable Markdown support.  (Markdown allows inline HTML, so I didn't reformat anything I didn't have to.  Tomorrow I may convert the whole thing to Markdown.)

Alerts: Update SPV Mining Alert

---

README.md
_alerts/2015-07-04-spv-mining.html
_layouts/base.html
_less/screen.less
_plugins/alerts.rb

README: https://github.com/saivann/bitcoin.org/tree/alertclass#alerts
Screenshot of pre-selected colors:

Allow to set styles for alert banner

---

_includes/guide_payment_processing.md

A small change that removes some information that has become outdated or unnecessary since I first wrote this section 14 months ago.

Dev Docs: Remove Outdated Info From Payment Processing Section

---

_releases/0.11.0.md

Preview: http://dg4.dtrt.org/en/download and http://dg4.dtrt.org/en/release/v0.11.0
This updates the download links to point to 0.11.0 and adds the 0.11.0 release notes to the site. I'll keep it updated throughout the RC cycle, but it can be merged by anyone with commit access once 0.11.0 final is released (see TODO lists below).
Currently provides the release notes up to d26f951 (which looks like the final notes).
CC: @laanwj
Essential TODO:
Optional TODO (may be done in commits after merge):
Expected URLs for the Bitcoin Core binaries:
/bin/bitcoin-core-0.11.0/bitcoin-0.11.0-linux32.tar.gz
/bin/bitcoin-core-0.11.0/bitcoin-0.11.0-linux64.tar.gz
/bin/bitcoin-core-0.11.0/bitcoin-0.11.0-osx64.tar.gz
/bin/bitcoin-core-0.11.0/bitcoin-0.11.0-osx.dmg …

Releases: Add Bitcoin Core 0.11.0

---

_layouts/base.html
_less/ie.css
_less/rtl.less
_less/screen.less
_templates/choose-your-wallet.html
js/base.js
js/devsearch.js
js/events.js
js/ie.js
js/main.js

(This pull request replaces #931 and #932)
Live preview: http://bitcointest4.us.to/en/choose-your-wallet
This is an important re-design of the underlying javascript functions and CSS stylesheets used for navigation menus (top menu and wallet menu).
This pull request should fix several navigation bugs and issues for iOS, as well as speeding up navigation and preventing accidental clicks on Android, by making good use of the touch events.
The dropdown menus on mobile devices also now avoid using CSS :hover, and can be expanded or shrinked by clicking on the parent element of any menu entry. This avoids confusion and accidental clicks by moving elements on the screen only on user request.
The wallets are now also populated, displayed and hidden on click and not on mouseover, which prevents …

Rework menus for mobile compatibility

---

_alerts/2015-07-04-spv-mining.md

This PR removes the alert banner from every page of the site and changes the bolded text near the top of the alert to:
I'm not sure we should be disabling the alert banner: if I understand correctly, several large miners have decided to stay with SPV mining (or worse, previous-header-hash-only mining).
On the other hand, I'm not aware of any short-term proposals to restore SPV wallet confirmation reliability to what it was when every miner did full validation---so the alternative seems to be keeping this alert up indefinitely, and I don't want to do that.
Comments appreciated.

Alerts: Disable SPV Mining Alert

---

404.html
_includes/index.html
_templates/index.html
index.html

When working on #972, I discovered Bitcoin.org has three pages with nearly identical content:
- `/<language>/index.html` which provides the Bitcoin.org index page localized into each supported language
- `/index.html` which provides a fallback in case language redirection doesn't work.  This page is currently identical to the English localized index page.
- `/404.html` which provides the 404 error page, which includes a Javascript redirect to the localized index page plus fallback content that looks like an old version of the English localized index page.
This PR now builds all three pages from the same source so that if we change any text, we only have to change it once.  (No text changes are introduced in this PR, except that text displayed on the 404 page is now identical to the text …

Combine /index, /<lang>/index, and /404

---

_includes/layout/base/breadcrumbs.html
_includes/layout/base/content.html
_includes/layout/base/footer-js.html
_includes/layout/base/footer-license.html
_includes/layout/base/footer-menu.html
_includes/layout/base/footer-sponsor.html
_includes/layout/base/head-language-dropdown.html
_includes/layout/base/head-language-select.html
_includes/layout/base/head-logo.html
_includes/layout/base/head-menu.html
_includes/layout/base/head-mobile-menu.html
_includes/layout/base/html-head.html
_includes/layout/base/pagetop-alert.html
_includes/layout/base/pagetop-detect-mobile.html
_layouts/base.html
_layouts/glossary_entry.html
_less/screen.less
_translations/en.yml
en/developer-documentation.md
en/developer-examples.md
en/developer-glossary.html
en/developer-guide.md
en/developer-reference.md

Preview: http://dg1.dtrt.org/en/developer-documentation
This pull contains three commits:
1. **Split the base layout into multiple files:** this makes it easy to create alternative layouts for collections of pages while reusing as much code as possible (so updates are easy).  This pull does not use this feature, but I hope to use it in a future pull to create a "sub site" with a dozen pages dedicated to Bitcoin Core.
Note: this commit diff is quite ugly because it produces HTML output that is identical to current master HEAD.
2. **Add whitespace to base layouts:** this whitespace-only commit fixes the ugliness of the previous commit.
3. **Add breadcrumbs to dev docs:** this changes the base template to allow adding breadcrumbs to pages, and proceeds to add them to all dev docs.  They can …

Layouts: Allow Alternative Base Layouts & Add Breadcrumbs

---

README.md
_alerts/2012-02-18-protocol-change.html
_alerts/2012-03-16-critical-vulnerability.html
_alerts/2012-05-14-dos.html
_alerts/2013-03-11-chain-fork.html
_alerts/2013-03-15-upgrade-deadline.html
_alerts/2013-08-11-android.html
_alerts/2014-04-11-heartbleed.html
_alerts/2015-07-04-spv-mining.md
_plugins/alerts.rb

This is, I think, the last thing left on the todo list from #934
Preview: https://github.com/harding/bitcoin.org/tree/alert-docs#alerts

Site Docs: Add Details To Alert Creation Process

---

_includes/ref/bitcoin-core/rpcs/rpcs/settxfee.md

Currently, Bitcoin Core accepts 0 as an argument to settxfee, see settxfee() in https://github.com/bitcoin/bitcoin/blob/master/src/wallet/rpcwallet.cpp
I've updated the description of settxfee to reflect this.

Update settxfee description to match actual behavior

---

README.md
_templates/choose-your-wallet.html

This change was planned since a while and nearly all wallets avoid reusing change addresses by default now, including recently added wallets, so now seems like a good time to raise the bar.
The only exception is Hive for Mac, which might support it later. The Hive team is mostly focusing on Hive Web, which remains displayed on the website.

Make no address reuse with change addresses a requirement for wallets

---

_translations/en.yml

This is aimed at improving the sections of these three pages that pull #972 attempted to remove.  The basis for several of the changes here were contributed as diff comments to that PR.
(New text identical to the new text in Bitcoin For Businesses.)

Update text on Bitcoin For X pages

---

_translations/en.yml

This PR continues the work started in aborted pull #972.  It is split into two commits:
1. No text changes; just wrap existing text to allow word diffing the next commit.
2. Actual text changes.

Update text on FAQ & Innovation pages

---

_less/screen.less
_templates/press.html

This PR makes changes to the quotes section of the Press page.  It is, I hope, the last PR related to the changes started in aborted PR #972.  There are several commits:
1. Fix a CSS-based bug that prevents display of the open-quote on the left column.  This can be seen on the live site: https://bitcoin.org/en/press#quotes
2. Add a link to the [Bitcoin WikiQuotes](https://en.wikiquote.org/wiki/Bitcoin) page for even more quotes.  Although this page doesn't currently have many more quotes than we do, I hope that by linking to it, we'll encourage more people to contribute to it.
3. Replace quotes from Max Keiser and Timothy Lee with quotes from Paul Buchheit (GMail creator) and Brian Forde (MIT DCI director).  The replaced quotes described Bitcoin as, respectively, "cheapest" and …

Update quotes on Press page

---

_events.yml

[Inside Bitcoins Seoul](http://insidebitcoins.com/seoul/2015?utm_source=bitcoinorg&utm_medium=eventlisting&utm_campaign=bitcoinorgeventlistingibseoul)

Add Inside Bitcoins Seoul to events page

---

_events.yml

[Inside Bitcoins New York](http://insidebitcoins.com/new-york/2016)

Added Inside Bitcoins New York to events page

---

_less/ie.css
_less/rtl.less
_less/screen.less

This addresses at least one issue mentioned on #1014 , by allowing these elements to be displayed inline on the screen until the space is really stretch enough.
I should have left equivalent space for texts, so variable-width translations should still fit correctly in the available space. At least I have verified various ones without noticing any issue.
Live preview: http://bitcointest1.us.to/en/

Apply more graceful mobile stylesheet to landing page icons

---

_less/screen.less

Live preview: http://bitcointest1.us.to/en/
Some code samples cannot be read on mobiles. Although this solution isn't ideal as it makes the code overflow outside of the page, my impression is that it's better than cutting the content altogether.

Allow code samples to overflow on mobiles in the documentation

---

_includes/layout/base/footer-sponsor.html

Current sponsorship will end on September 1th.
It is not decided yet if the Foundation will renew it's support (which I'd be happy with as far as I'm concerned). In the mean time, the sponsorship banner can be put on hold.
Note; This pull request should not be merged until September 1th.

Drop inactive sponsorship banner

---

_includes/ref/bitcoin-core/rpcs/intro.md
_includes/references.md

This PR contains a polished and expanded version of the developer reference section that describes the Bitcoin Core RPC interface. Site tests are passing on my laptop and on [Travis CI](https://travis-ci.org/carnesen/bitcoin.org). A preview of the changes can be found here:
http://bitcoin-dot-org.carnesen.com/en/developer-reference#remote-procedure-calls-rpcs
For comparison here's that section on the site currently:
https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs
The changes in this PR are limited to the RPC interface description up to where the "Quick Reference" starts.
Feedback is welcomed, and I'd be happy to explain why I made any of these changes, just let me know.

Polish and expand Bitcoin Core RPC interface intro in developer reference

---

_templates/about-us.html
_translations/en.yml

I just realized the Foundation wasn't on the contributors list yet. I'd like to correct that omission.
In the absence of critical feedback, this pull request will be merged on September 5th.

Add The Bitcoin Foundation as a sponsor in the list of contributors

---

.travis.yml
README.md
_build/update_site.sh
_build/update_txpreview.sh
_plugins/env.rb
_templates/about-us.html
_templates/download.html
robots.txt

This PR has three commits:
1. A new plugin which makes environmental variables (env vars) starting with `BITCOINORG_` available as template variables.
2. A conditional to the robots.txt file that prevents the site from being indexed if an env var is set to "preview".  This is useful for @saivann and myself who host previews of the site but don't want them to appear in search engine results.  Documentation for this is also added to README.md
3. A conditional on two of the content pages that changes how they will appear on cloned versions of the site (of which there are now several besides bitcoin.com).  Specifically:
- The Bitcoin Core download page on cloned sites redirects to the language equivalent page on Bitcoin.org
- The About Us page has all information replaced by a single …

Conditionally build some pages differently based on environmental variables

---

.gitignore
Makefile
_plugins/contributors.rb
_plugins/events.rb

When making changes to the site, Saïvann and I often diff the resulting HTML output with output from earlier known-good commits.  One problem with this method is that the HTML output isn't fully deterministic---some of it comes from external sites and can change massively between two builds that are only minutes apart, making reading the diff unpleasant and less useful than it could be.
This commit caches that external data between builds so that two builds on the same computer are very nearly deterministic.  As evidence, at the end of this message I offer inline the full diff of two sequential builds both on this commit.
Cached Meetup.com events, Bitcoin Core contributor listings, and Bitcoin.org contributor listings are retained for 24 hours before being refreshed.  Cached Geo-location …

Backend: cache events and contributor listings

---

_includes/devdoc/guide_transactions.md
_includes/references.md

As reported by @jonasschnelli, the docs don't mention that IsStandard() checks on redeem scripts were relaxed in https://github.com/bitcoin/bitcoin/pull/4365.  This fixes that and also mentions the restrictions on use of the NOP op codes added in https://github.com/bitcoin/bitcoin/pull/5000

Dev Docs: Update description of P2SH standardness

---

_releases/0.11.1.md

This adds the Bitcoin Core 0.11.1 release to Bitcoin.org, making it the recommended release shown on the Download page.
The file names we're expecting for the binaries are:
/bin/bitcoin-core-0.11.1/bitcoin-0.11.1-win64-setup.exe
/bin/bitcoin-core-0.11.1/bitcoin-0.11.1-win32-setup.exe
/bin/bitcoin-core-0.11.1/bitcoin-0.11.1-win64.zip
/bin/bitcoin-core-0.11.1/bitcoin-0.11.1-win32.zip
/bin/bitcoin-core-0.11.1/bitcoin-0.11.1-osx.dmg
/bin/bitcoin-core-0.11.1/bitcoin-0.11.1-osx64.tar.gz
/bin/bitcoin-core-0.11.1/bitcoin-0.11.1-linux64.tar.gz
/bin/bitcoin-core-0.11.1/bitcoin-0.11.1-linux32.tar.gz
/bin/bitcoin-core-0.11.1/bitcoin-0.11.1.tar.gz
/bin/bitcoin-core-0.11.1/SHA256SUMS.asc
(Since these paths don't currently exist, the Travis CI build will fail.  That's ok.)
@laanwj Note, if you merge …

Releases: Bitcoin Core 0.11.1

---

_templates/about-us.html
_translations/en.yml

@mateuszrybin suggested we could use BrowserStack for testing the site on several devices and suggested they were offering the service free of charge to open-source projects.
After a quick email with them, they are indeed happy about providing the service in exchange for a backlink in our "About us" page. This pull request is submitting that link for review (see screenshot below).
I personally think this is a very useful tool to have, and what we're asked to provide in exchange seems very reasonable to me.

Add BrowserStack to the Contributors section

---

_includes/devdoc/bitcoin-core/api-intro.md

Small typo fix: "rational" -> "rationale"
Initially submitted as part of #1102, but breaking out for easy inclusion.

typo: changed rational to rationale

---

_includes/devdoc/guide_wallets.md

Fixed a typo. The ECC equation had x and y mixed up.
References:
- Section 2.4.1 of http://www.secg.org/sec2-v2.pdf
- https://en.wikipedia.org/wiki/Elliptic_curve_cryptography

correct ecc equation

---

_config.yml
_data/glossary/en/null-data-transaction.yaml
_data/glossary/en/op-code.yaml
_data/glossary/en/p2sh-address.yaml
_data/glossary/en/p2sh-multisig.yaml
_includes/devdoc/bitcoin-core/rpcs/rpcs/decodescript.md
_includes/devdoc/bitcoin-core/rpcs/rpcs/gettxout.md
_includes/devdoc/guide_contracts.md
_includes/devdoc/guide_transactions.md
_includes/devdoc/ref_p2p_networking.md
_includes/devdoc/ref_transactions.md
_includes/helpers/vars.md
_includes/references.md
_posts/2015-03-05-quarterly-report-decjanfeb2015.md
_posts/2015-04-14-new-glossary.md
en/developer-glossary.html

As suggested by @laanwj in #1068
I checked, and I couldn't find any images on the site that used "op code", so this is a pure text replacement (done semi-manually to ensure correctness, not with sed).

Dev docs: change "op code" to "opcode"

---

_templates/choose-your-wallet.html

#1121 removed a separator indicating the end of the header information, resulting in a [broken page](https://bitcoin.org/en/choose-your-wallet)

Undo removal of end of header in #1121

---

_includes/devdoc/bitcoin-core/api-intro.md

This tries to quickly solve some of the issues raised in #1061 and #1102 about the description of endianness in the hash byte order text.
In my opinion, simply thinking about hashes as having endianness tends to confuse developers, since hashes are usually treated as byte arrays rather than numbers.  This PR simply drops the references to endianness in the hopes of minimizing confusion to new developers as well as allowing established developers to spend less time arguing about whether header hashes in Bitcoin are little or big endian.
I'm 100% open to a better patch that describes all the relevant considerations so far discussed, although I think it might be better to put that on the Wiki and then link to it from here.  (That's a suggestion; feel free to PR it here if you think it's …

Dev Docs: drop mention of endianness in hash byte order

---

_includes/devdoc/ref_block_chain.md

As reported in #1106, our text for v4 blocks had become outdated.  This corrects it and also mentions IsSuperMajority() and version bits as soft fork management methods, although I don't currently have the time to write up a more detailed description of either method.
Preview with this commit applied:

Dev Docs: update v4 blocks text; mention version bits

---

en/full-node.md

The launch agent part of this guide is still waiting on [this PR](https://github.com/bitcoin/bitcoin/pull/6621)

added instructions for setting up bitcoind on OS X

---

_alerts/2015-10-12-upnp-vulnerability.md

The red banner at the top of the site went up on Oct 12th.  I suggest we take it down on Sunday, Nov 1st.
The alert notice text will still be available at all the same URLs on the site as before, so anyone who is still catching up on their bitcoin-dev email from two weeks ago will still be able to read it.
CC: @laanwj

Alerts: drop banner for UPnP vulnerability

---

_releases/0.10.3.md

This adds the Bitcoin Core 0.10.3 release notes to bitcoin.org.
I tried to mirror for pull requests for other releases, and for the date I used the date of the release tag. Links were wrapped with `<`, `>`.
The magnet link is missing, and I'm not sure where/how to find the torrent.

Releases: Bitcoin Core 0.10.3

---

_releases/0.11.2.md

Previews:
- Release notes: http://dg1.dtrt.org/en/release/v0.11.2
- Download: http://dg1.dtrt.org/en/download
This adds the Bitcoin Core 0.11.2 release to Bitcoin.org, making it the recommended release shown on the Download page. The release notes are current as of https://github.com/bitcoin/bitcoin/commit/7e278929df53e1fb4191bc5ba3176a177ce718bf
Essential TODO:
Optional TODO (may be done in commits after merge):
The file names we're expecting for the binaries are:
/bin/bitcoin-core-0.11.2/bitcoin-0.11.2-win64-setup.exe
/bin/bitcoin-core-0.11.2/bitcoin-0.11.2-win32-setup.exe
/bin/bitcoin-core-0.11.2/bitcoin-0.11.2-win64.zip
/bin/bitcoin-core-0.11.2/bitcoin-0.11.2-win32.zip
/bin/bitcoin-core-0.11.2/bitcoin-0.11.2-osx.dmg
/bin/bitcoin-core-0.11.2/bitcoin-0.11.2-osx64.tar.gz …

Release: Bitcoin Core 0.11.2

---

_includes/layout/base-core/footer-license.html
_includes/layout/base-core/footer-menu.html
_includes/references.md
_layouts/base-core.html
en/bitcoin-core/about-site.md

This commit makes two changes.  First it modifies the footer on the Bitcoin Core pages:
This drops the [Press](https://bitcoin.org/en/press) page and the [Blog](https://bitcoin.org/en/blog) page and changes the About link to the page described below.  Beneath the copyright statement, a short message tells readers that the Bitcoin Core pages are not a normal part of the site; the link here also points to the page described below.
The second change is a new page that describes the relationship between Bitcoin Core and Bitcoin.org in detail:
All the text in both changes is just draft text, so please feel free to make suggestions.  In addition, I'm open to combing this with #1186 if a more visible disclaimer is desired for the main page.  What I tried to aim for with this PR is a short and …

Core: mention separation of concerns from Bitcoin.org

---

en/bitcoin-core/capacity-increases-faq.md

Segwit is a block size increase, lots of readers of this FAQ care more about the block size than all the goodness of segwit.
So I think this should be clearer.

Making clear that segwit is equivalent to a block size increase

---

en/bitcoin-core/capacity-increases-faq.md

I'm told some people were confusing the FAQ itself for the roadmap; this should help remove the confusion.  This becomes the first question/answer in the document:

Capacity Increases FAQ: more prominently link to roadmap

---

en/full-node.md

Change references from 'getaddr.bitnodes.io' in the running a full node page, to 'bitnodes.21.co' and rename it from the Getaddr page to Bitnodes page.

Change references to 'getaddr.bitnodes.io'

---

_includes/layout/base-core/pagetop-moved-notice.html
_layouts/base-core.html
_less/screen.less
_translations/en.yml
de/bitcoin-core/2016-01-07-statement.md
en/bitcoin-core/2016-01-07-statement.md
en/bitcoin-core/capacity-increases-faq.md
en/bitcoin-core/capacity-increases.md
en/bitcoin-core/index.md
es/bitcoin-core/2016-01-07-statement.md
it/bitcoin-core/capacity-increases-faq.md
it/bitcoin-core/capacity-increases.md
ru/bitcoin-core/2016-01-07-statement.md
zh_CN/bitcoin-core/2016-01-07-statement.md
zh_CN/bitcoin-core/capacity-increases-faq.md
zh_CN/bitcoin-core/capacity-increases.md
zh_TW/bitcoin-core/2016-01-07-statement.md
zh_TW/bitcoin-core/capacity-increases-faq.md
zh_TW/bitcoin-core/capacity-increases.md

This is an alternative to #1205 that adds banners to pages that are now mirrored on BitcoinCore.org.  The banners look like this and redirect to the specific page:
In addition, a link is added to the News on the main Bitcoin.org Bitcoin Core page pointing to the new website:
Full preview: http://dg2.dtrt.org/en/bitcoin-core/

Bitcoin Core: add banner redirecting some pages to BitcoinCore.org

---

_includes/devdoc/guide_transactions.md

Correct spelling of 'desciption' to description and 'programable' to programmable.

guide_transactions.md, correct 2 spellings.

---

_templates/resources.html

On the resources page (https://bitcoin.org/en/resources) directories section the link for givebtc.org redirects to http://bitcoinembassy.ca

Remove givebtc.org from resources

---

_templates/community.html

On the community page (https://bitcoin.org/en/community#mexico), the
‘Fundación Satoshi Nakamoto’  website does not load and should be
removed.

Remove btcmexico.org from community page

---

_data/glossary/en/null-data-transaction.yaml
_includes/devdoc/guide_transactions.md

https://github.com/bitcoin/bitcoin/pull/5286 increased `MAX_OP_RETURN_RELAY` to 80 bytes.

OP_RETURN can accept 80 bytes

---

_data/glossary/en/null-data-transaction.yaml
_includes/devdoc/guide_transactions.md

PR #1129 pointed out that the null data transaction details were out of date.  Other comments on that PR asked that the tx type be better explained.  I submitted a PR to the repository of that PR which provided what I think was a better explanation, but I haven't heard from that author in two months, so I'm submitting it separately here.

Dev Docs: clarify null data conditions

---

_templates/press.html

The bitcoinpresscenter.org site is not necessary any more and will not be maintained. Removing from bitcoin.org press page.

Remove volunteerpresscenter (bitcoinpresscenter.org)

---

_releases/v0.12.0.md
en/bitcoin-core/index.md

Preview: http://dg1.dtrt.org/en/download
TODO:
Note that this patch also drops the Jan2016 project statement and capacity-increases-related links from the Bitcoin.org/bitcoin-core main page as they were statically sorted, so so would've appeared higher in the listing than the 0.12.0 release announcement.  The *new website* link is left in and placed above the 0.12.0 announcement so that people still go to the new website.  Preview:
I've dropped my commit access on Bitcoin.org for busy-ness reasons, so someone else will have to merge this when appropriate.  Also, if someone could tag this now as Releases and Bitcoin Core, that would be useful.

Bitcoin Core: 0.12.0 release notes

---

_events.yml

See:
https://twitter.com/coindesk/status/707248723458400256
http://www.bitcoinerrorlog.com/2016/03/08/coindesk-promotes-london-bitcoin-forum-scam-sweeps-under-rug/
https://www.reddit.com/r/Bitcoin/comments/49iqp5/coindesk_promotes_london_bitcoin_forum_scam/

Remove fake event.

---

en/bitcoin-core/capacity-increases-faq.md
it/bitcoin-core/capacity-increases-faq.md

Link to bip is dead, Core version updated the link in https://github.com/bitcoin-core/bitcoincore.org/commit/7bd3ad9484802dd9a623e5586f8a2da3f92a2cd6 but this page still has the dead link.

Fix incorrect link to segwit bip

---

_includes/devdoc/guide_mining.md

Minor clarification that getwork is only applicable for v0.9.5 and below.

Clarify solo mining version applicability

---

_templates/resources.html

Coinfox doesn't really offer any added value. It's just blogspam with rewrites of articles by myself and others. Recent example: http://www.coinfox.info/news/5057-cory-fields-health-bitcoin is a rewrite of http://coinjournal.net/mits-cory-fields-contentiousness-in-bitcoin-is-sign-of-good-health/ where the featured image is copied.
The business model of coinfox seems to be taking the top posts from the previous day on /r/bitcoin, rewriting them, and reposting them the next day.

remove Coinfox from resources.html

---

_translations/en.yml

The wording "almost just like with physical money" is awkward. Removed the extraneous "just": "almost like with physical money"

improve wording

---

README.md

I recommend making the optional "avoid address reuse" criteria mandatory.  All currently listed wallets meet this criteria.
In the future, I may recommend adjusting the privacy scoring since this criteria is the only requirement for a passing score.

Move avoiding address reuse criteria from optional to required

---

_data/glossary/en/pubkey-script.yaml

Readers could get the impression that the script for fulfilling the conditions is called scriptPubKey in code (which is not true).

Clarify that Pubkey Scripts are called scriptPubKe

---

_includes/devdoc/ref_p2p_networking.md

Fixed type error in first table dev reference merkleblock, change 32 bits in 32 bytes refered to the size of a tx or merkle node hash

fixed type error in first table dev reference merkleblock

---

_alerts/2016-10-14-alert-retirement.md
_alerts/2016-10-17-alert-retirement.md

As per discussion on the -core-dev IRC, here is the post for the retirement of the alert system. The actual alert will happen tomorrow. This post should go up today before the actual alert as a pre-warning warning.
IRC Discussion of this post: https://botbot.me/freenode/bitcoin-core-dev/2016-10-13/?msg=74784693&page=6

Alert system retirement notice

---

_releases/v0.12.0.md
_releases/v0.13.0.md

Somewhat late to fix now, but meh...

Trivial: Sync 0.12/0.13 release notes with bitcoin/master

---

_alerts/2016-10-17-alert-retirement.md

Pushing back the prefinal alert date because the RC process for 0.13.1 has already started.
See: https://botbot.me/freenode/bitcoin-core-dev/2016-10-17/?msg=74970645&page=5

Push back prefinal alert date

---

_includes/devdoc/ref_p2p_networking.md
_includes/references.md

These were first implemented in Bitcoin Core 0.13.0.
Closes #1364.

Add mention of protocol version 70013 and 70014

---

_templates/choose-your-wallet.html

The Android version of breadwallet came out a couple months ago.

Adding Android as supported OS for breadwallet

---

_includes/devdoc/ref_block_chain.md

Fixed typo version data type in block headers. Based on issue #1413

Changed version data type to signed int32

---

_templates/resources.html

CCN  has covered Bitcoin news since the middle of 2013. June, July, or August. Don't recall. Not long after CoinDesk got started.

Added CCN.la to Resources.html

---

_templates/community.html

First of all, I remove in this request two forums of community, the first is forobtc.com that don't have any hosting or website running. The second one is forobitco.in only used at now for spaming cloud mining, faucet referals and tiered link building.
The second thing I did was add a new alternative forum in Spanish about bitcoin and other decentralized applications.

Added a new Bitcoin forum and eliminated two disused

---

_templates/resources.html
_translations/en.yml

At present on our [Resources page](https://bitcoin.org/en/resources), the first link is to the [Bitcoin
Foundation](https://bitcoinfoundation.org/). That website has fallen into disrepair and is currently
broken.
Each day new users are discovering Bitcoin for the first time,
along with others who are learning more about it via Bitcoin.org. This
PR removes the link to the Bitcoin Foundation, for now, so we aren't
providing a top resource pointing to a broken web page:

resources: Remove Bitcoin Foundation

---

_templates/choose-your-wallet.html

I did not find a clear page defining what the various properties like "checkfailtransparencynew" mean.  Is there something better we can link to?

choose-your-wallet: Adding info about wallet properties.

---

_templates/resources.html

This adds Buy Bitcoin Worldwide to the resources page. 
This is an important tool for new users who want to buy bitcoin in their country. The country directory is here: https://www.buybitcoinworldwide.com/en/ . It is available in 13 languages. 
Another tool that helps people buy bitcoin based on location and payment method: https://www.buybitcoinworldwide.com/coinfind/

Add Buy Bitcoin Worldwide to Directories

---

_includes/devdoc/guide_transactions.md

A few unrelated lines also had trailing whitespace which was also removed.

Updating info on high-priority-transactions

---

_data/glossary/en/double-spend.yaml

Please see the following issue for context: #1248 
TLDR: I believe the definition for "double-spend" should not contain the words "spend" or "spent" 
and should be more specific and clear to differentiate from the pre-Bitcoin definition of double-spend.
I am not proficient in Github or programming in general, so hopefully this pull request is 
appropriate and done correctly. If this is successful, I will also attempt to create a new glossary term
for "spend/spent" and others that may be helpful.

Update to Glossary Definition: Double Spend

---

README.md

The full node page is no longer "upcoming" and the link should point to:
https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/en/full-node.md
**Edit:** Changed to https://bitcoin.org/en/full-node as requested.

README: Updating link to full node page.

---

README.md
_templates/about-us.html

This PR updates the README to include my contact information and also updates myself to Active on the About page.
Unless others object, this will be merged on Sunday, December 18th.

Add my contact info to README; Update self to Active

---

README.md

Requiring HSTS preloading reduces the risk of MITM attacks for users who have not previously visited a particular site before and is especially useful for preventing downgrade attacks on TOR users or users who use browsers without persistent storage. bitcoin.org itself currently doesn't use HSTS preloading and it would be a good idea to enable it there as well.

add HSTS preload requirement for wallets

---

_templates/resources.html

I'm not sure why this site was added. It doesn't offer much of anything that you wouldn't find on the more established sites. There is little to no unique/original content, and there is apparently no fact checking before something is published. Latest example is an article claiming Phil Potter is a Bitcoin core dev while also getting his Bitfinex job title wrong (among other errors): https://www.cryptocoinsnews.com/bitfinex-cso-theres-chinese-political-effort-delay-block-segwit/

Remove CryptoCoinsNews from News Resources

---

_templates/choose-your-wallet.html

As of release [1.87](https://github.com/greenaddress/GreenBits/releases/tag/r1.87) of September 4th 2016 (now 1.93) GreenBits supports generic socks5 and explicit onion support with Orbot.
This PR updates the GreenBits wallet listing with the current released status.

GreenBits now supports Tor for both SPV and GreenAddress bc data/sign

---

en/full-node.md

This PR adds additional info to the [Running a Full Node](https://bitcoin.org/en/full-node) page regarding how to configure a node to `prune` in order to reduce storage requirements:
Unless others object, this will be merged on Wednesday, January 4th.

full-node: Add info on setting node to prune to reduce storage

---

_includes/devdoc/guide_wallets.md

Instances of `point( ( key + i ) % G )` should read `point( (key + i) % p )`

Take remainder from the curve's prime instead of G

---

_events.yml

This adds an upcoming Bitcoin Brunch event in The Netherlands:
https://www.arnhembitcoinstad.nl/#usergroup
Unless others object, this will be merged on Wednesday, January 25th.
// Closes #1486

events: Add Bitcoin Brunch on Intl Day of Privacy

---

_includes/layout/base/head-menu.html

This fixes a missing link to the Resources page as noted in #1495.
// Fixes #1495

resources: Fix broken link to Resources page

---

_templates/exchanges.html

This removes Huobi and OKCoin from the Exchanges page for the interim in light of:
http://www.coindesk.com/two-chinas-biggest-exchanges-stop-bitcoin-withdrawals/

exchanges: Remove Huobi and OKCoin

---

_less/screen.less

I think the hover effect for subhead links (Edit | History | Report Issue | Discuss) is distracting and unnecessary.

Remove hover effect for subhead links (Developer Reference)

---

_templates/resources.html

Added BitcoinAverage under _Ressources->Charts_ and 3 local news sites to _News_.
- BitcoinBlog.de - Most popular German bitcoin blog
- satoshi.pl - Requested in #1372 . Looks like a decent blog
- Bits Media - Formerly BTCsec, probably the oldest Russian bitcoin site

Added local news sites and BitcoinAverage

---

_templates/choose-your-wallet.html

TREZOR has been here for a few years already and is used by several thousands of people all around the world, so I think it deserves more than just a "New app" ranking.
I used `transparency: "checkgoodtransparencydeterministic"`, because our firmware can be built deterministically using Docker and one can verify that the fingerprint of the firmware distributed by us is the same as the fingerprint of the firmware built locally.
Also the product name is TREZOR, not Trezor.

update info about TREZOR hardware wallet

---

_events.yml

This adds an upcoming event, the Future of Fintech to the site.
Unless others object, this will be merged on Sunday, February 12th.
// Closes #1492.

event: Add Future of Fintech

---

_templates/choose-your-wallet.html

This PR changes the iTunes account we use for the GreenAddress app on iOS.
The app is otherwise unchanged (though we also added the testnet version now to the new iTunes account)

update iTunes account for GreenAddress iOS app

---

_events.yml

This PR:
- Adds a new event, The Blockchain Expo
- Fixes formatting of USA across some different event entries for consistency
- Fixes an event that had an incorrect country associated with it
Unless others object, this will be merged on Sunday, March 5th.
Closes #1521 .

events: Add Blockchain Expo, Fix formatting of USA & Incorrect Country

---

_plugins/contributors.rb
_templates/about-us.html
_templates/development.html

GitHub recently made a change on their end to the URLs with which
profile images are stored. As a result, this has caused the profile
images on the About Us page to break, and tests to fail.
This PR resolves the issue.

contributors: Fix broken test

---

docs/adding-events-release-notes-and-alerts.md

This fixes an issue in the documentation for Bitcoin.org, on how to add
an event to the site. The link to the Events page as well as the event
template needed to be updated.

docs: Fix broken link when adding an event

---

google40ba4724029a01dd.html
google8f9b63d5ea1da1f8.html

This updates an old verification link to webmaster tools with a new one,
so that it will be possible to tell if there are any crawl errors or 404s on the
site. This is important because if there are, Bitcoin.org can get
penalized in search results thereby making it rank further down below
other Bitcoin websites that are competitively trying to secure top
positions and rank higher.

webmaster_tools: Update verification link

---

_events.yml

This adds a few new upcoming events to the [events page](https://bitcoin.org/en/events):
+ http://www.theblockchain.nz/
+ https://www.meetup.com/Article-78-Against-NYDFS/events/238080585
+ https://www.eventbrite.co.uk/e/an-introduction-to-crypto-currencies-bitcoin-the-blockchain-tickets-32417523686

Add new upcoming events

---

_includes/references.md

This fixes a broken link in the developer documentation to a [payment request generator](https://bitcoin.org/en/developer-examples#payment-processing). This will be merged once tests pass.
Closes #1527

references: Fix broken link to PRG

---

_alerts/2016-11-01-alert-retirement.md

Now that 0.14.0 has been released, this ends the notification about the
retirement of the alert system, which has been running and displaying on
the tops of all pages on Bitcoin.org for the last 4 months (to give
everyone advance notice).
Unless others object, this will be merged on Sunday, March 12th.

alert: Drop current alert notification

---

_autocrossref.yaml
_config.yml
_includes/devdoc/ref_p2p_networking.md
_includes/references.md

This PR adds documentation for the `feefilter` message type, added in Bitcoin Core V0.13.0.

add feefilter documentation

---

_data/glossary/en/input.yaml

This resolves an issue where the number of fields for an input was
incorrectly worded as four instead of three.
// Resolves #1542

glossary: Fix typo in number of fields

---

_templates/community.html

Resolves #1546
Context from @odv:
```
Hello!
I was browsing bitcoin.org and noticed a spam link listed in the
Community section, under Romania called Fundatia Bitcoin Romania.
https://bitcoin.org/en/community#romania
If you go to that page, below the first post, there is a masked
advertisement for a romanian webcam studio and two other posts about a
particular person that got rich by selling flowers. I won't list his
name here but he's quite a known scammer in the romanian internet space.
If you check out his twitter handle he has a lot of retweets about
romanian webcam studios which to me makes it pretty clear that he's
behind this site too.
The Nov 17 and Nov 24 posts have a link to another site that has just
one posts, again, about that same individual. If you query …
```

community: Remove Fundatia Bitcoin Romania

---

_includes/devdoc/ref_p2p_networking.md

An incorrect protocol version was referenced. It should be `60001`, not
`60000`.
This will be merged as soon as tests pass.
// Closes #1548

ref_p2p_networking: Fix protocol version

---

_templates/exchanges.html

This adds Bitwage to the list of International exchanges. They allow
people to receive some or all of their wage payments, salaries, etc.,
in bitcoin.
Unless others object, this will be merged on Sunday, March 26th.

exchanges: Add Bitwage

---

CODE_OF_CONDUCT.md
docs/adding-events-release-notes-and-alerts.md
docs/become-a-contributor.md
docs/setting-up-your-environment.md

This PR fixes a few broken links in the repository documentation, and also corrects some markdown formatting issues in some of the excerpts / snippets.

Repository documentation fixes

---

_templates/resources.html

Bitrefill sells vouchers and refills of prepaid phones used by 75% of mobile users worldwide. This is one of the most common purchases for bitcoin users all over the world. Supports > 150 countries, in many of which this is the only thing that can be purchased with bitcoin today.

Add Bitrefill to "Vouchers" section

---

_templates/exchanges.html

I added a few Japanese and Korean exchanges.
I think for some exchanges the country classification needs to be changed. Paymium, Bitcoin.de and Rocked Trading are open to all SEPA supporting countries and have multilingual sites. Maybe a EU/Euro category would make sense.
While Bitwage is a great service I would not consider it an exchange or a way to buy/sell bitcoin.

Added JP/KR exchanges

---

_alerts/2016-11-01-alert-retirement.md

If there is a known date for the alert key being published, I'm happy to add that too.
The date column states "_1-2 months after the Final Alert_" which has already passed. :-/

Updating 'alert system retirement' page.

---

js/main.js

Closes #1493
Preview: http://dg1.dtrt.org/en/choose-your-wallet
Currently when you load the page in a mobile browser and click on a wallet, a copy of that that wallet's entry is copied using JS to a box later in the page where you can read about the wallet details.  When you change platform, all the currently displayed wallet icons are cleared and then refilled with the icons for the newly-selected platform, with a check running that ensure each wallet is only displayed once (which is important for combination categories such as "mobile" where we don't want to show the same wallet twice just because it has an Android and iOS version).
Since the wallet details box in the mobile display wasn't cleared when you changed platform, the check that prevents duplicate wallet displays thought that …

Wallets: fix accidental wallet hiding on category change

---

en/full-node.md

Closes #1544 (CC: @chris-belcher )
I tried checking my assertions about bandwidth usage by starting my node with `-blocksonly` and then using `bitcoin-cli getnettotals`, but the bandwidth reported used by that was 20% *less* than the combined size of the blocks I downloaded during the 90 minute test according to `bitcoin-cli getblock <hash> | jq .size`.
It's possible this is for some reason I don't know, but my guess is that it's because I had a saved mempool from before my restart so my node was able to make use of compact blocks.  However, the overhead for the upload bandwidth is consistent with the 1 MB I estimated and so I think we're fine saying 150 MB download bandwidth to account for changing peer connections and occasional stale blocks, plus the occasional fun times when someone …

Full node guide: describe blocks-only mode

---

_templates/resources.html

Hello.
I think this website would be an useful addition for the Charts page. It calculates the [historical volatility](http://www.ivolatility.com/help/2.html) of the Bitcoin price using the [Coindesk API](http://www.coindesk.com/api/) (which will change to BitcoinAverage soon && more features will be added). Volatility is a very important metric as Bitcoin is slowing moving towards stability that can be seen in traditional fiat currencies, and was used as an argument against Bitcoin in the past.
I would like to hear other people's input. Any suggestions for the [website ](https://bitvol.info)are also very welcome!

Add BitVol to Resources/Charts

---

Makefile
_less/screen.less
_templates/choose-your-wallet.html

Closes #1569
Preview: http://dg0.dtrt.org/en/choose-your-wallet
This uses @Mirobit's suggestion from the above issue to expand the display to show up to 14 wallets at a time, which is the maximum number of entries we have in any category except for the main page (which contais 18 wallets).
I've tested on Firefox 45 ESR for Linux, Chromium for Linux, and Chrome for Android.  Testing on other browsers appreciated.
In addition, wallet additions made after this PR is merged will cause a test to fail if any category begins to contain more than 14 wallets.  That way we shouldn't be surprised by wallets not being shown in the future.  We can discuss what to do about the problem then.
As part of the above, I made minor fixes to the entries for Electrum and Coin.Space that caused not all of their …

Wallets: show up to 14 wallets

---

_includes/devdoc/guide_p2p_network.md
_includes/devdoc/ref_p2p_networking.md
_includes/references.md

Now that v0.14.0 has shipped, it seemed like a good idea to update this info.
Suggestions / modifications welcome!
Most of this info was gathered from:
* https://github.com/bitcoin/bitcoin/pull/7692
* https://bitcoin.org/en/alert/2016-11-01-alert-retirement

P2P 'alert' messaging was removed, updating DevDocs (also updating protocol table to 70015)

---

_includes/devdoc/guide_wallets.md

"work" was missing in the first sentence describing the point() function.

Fixed Missing word in guide_wallets.md

---

Gemfile
Gemfile.lock
Makefile
_contrib/schema-validator.rb
_templates/choose-your-wallet.html
docs/managing-wallets.md
quality-assurance/schemas/wallets.yaml

As mentioned in #1592, I wanted to validate the 1,100-line wallet YAML to ensure consistency between entries.  I also wanted to better document the entry format since even I sometimes wonder which option does what.
This PR validates the wallet entries against a pretty strict schema.  It's not perfect---I've put in some TODOs where we could be more strict with changes to the current format---but I think it's better than nothing.
**Some examples:**
In #1592, I discovered Electrum declared an `android` platform without declaring a default `mobile` platform, so it wasn't being counted as a mobile wallet.  If that problem hadn't already been fixed, the schema would've caught it:
```text
user@devbco:~/bitcoin.org$ make check-validate-yaml 
The property '#/wallets/4/electrum/platform' has a …
```

Wallets: validate wallet YAML file using JSON Schema

---

README.md

This adds a section to the repository README letting people know it's now possible to earn bitcoin in some cases and get paid for making contributions to Bitcoin.org. In particular, I'm testing this out with some issues that have been open for over a year, and some other small ones that no one has stepped up to resolve.
These open issues are [labeled with a "₿"](https://github.com/bitcoin-dot-org/bitcoin.org/labels/%E2%82%BF), which means that they now have bounties on them. Anyone can submit a pull request resolving the issue along with an accompanying note or comment containing a bitcoin address to automatically receive a payment in the amount of the bounty if it gets merged.
This is an important experiment to run, because it will enable Bitcoin.org to potentially:
- Knock out some …

README: Add section, Earn Bitcoin for Contributing

---

README.md

This updates the Bitcoin symbol to "Bounty" based on [feedback from achow101](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1606#issuecomment-302941982) and will be merged once tests pass.
cc: @achow101

README: Change Bitcoin Symbol to 'Bounty'

---

_includes/devdoc/bitcoin-core/rpcs/rpcs/importaddress.md
_includes/devdoc/ref_p2p_networking.md
_includes/devdoc/ref_transactions.md

Corrected Compact Size Unsigned Integer description to include the lower bounds.
Changed reject message code descriptions of the extra data field to be more accurate as the extra data is not always what was specified nor is the field required.
Clarified the empty message headers are allowed.
Removed incorrect note in importaddress which stated that addresses would not be rescanned if already in the wallet. They are rescanned.
Closes #1505, #1365, #1604, #1520 
If this is accepted, please pay the bounty to 1AjFwHanPewurVms4Z3ExtapHmKWF6aTVS

Various corrections to developer reference

---

_autocrossref.yaml
_data/glossary/en/block-size-limit.yaml
_data/glossary/en/masf.yaml
_data/glossary/en/node.yaml
_data/glossary/en/uasf.yaml
_includes/devdoc/bitcoin-core/rpcs/rpcs/listbanned.md
_includes/devdoc/guide_block_chain.md
_includes/devdoc/guide_p2p_network.md
_includes/references.md

Added the following new glossary terms:
- UASF
- MASF
- Node
- ~Full node~
- ~Archival node~
- ~Pruned node~
- Block size limit
Closes #1605, #1539, #1240 
If this is accepted, please pay the bounty to 1AjFwHanPewurVms4Z3ExtapHmKWF6aTVS

New glossary terms

---

_plugins/events.rb
_templates/events.html
docs/adding-events-release-notes-and-alerts.md
docs/setting-up-your-environment.md

Closes #1617 
In testing, the only rendered HTML changes to the site were three fewer lines of whitespace per rendered translation of the Events page.
I also checked the Events RSS feed and it appeared that we never included any Meetups information in it, so no changes were required there.

Events plugin: stop requesting events from Meetup.com

---

_includes/devdoc/bitcoin-core/rpcs/rpcs/fundrawtransaction.md
_includes/devdoc/bitcoin-core/rpcs/rpcs/sendmany.md
_includes/devdoc/bitcoin-core/rpcs/rpcs/sendtoaddress.md

Functionality was merged into Bitcoin Core in March '15 which I think is Bitcoin Core 0.10.1?
Here it is in the latest version: https://github.com/bitcoin/bitcoin/blob/e4918316d80f0541189c40039095c716a09d636e/src/wallet/rpcwallet.cpp#L403

Add subtractfeeamount parameter

---

Makefile

Since the incremental build (#1643) update "make preview" leads to the following error:
` Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
Invalid US-ASCII character "\xE2" on line 2427
jekyll 3.0.1 | Error:  Invalid US-ASCII character "\xE2" on line 2427
`
I don't know if this is the best solution but it fixes the error.

Make preview charset fix

---

_alerts/2017-07-12-disruptive-forks.md
_alerts/2017-07-12-potential-split.md

This PR adds a warning for the chainsplit that may occur on 1 August 2017.  It's focused on describing to non-expert users what they should do to secure their funds and does not advocate any particular position on the fork or attempt to describe the background of the situation.
The warning is displayed in orange above every regular page on Bitcoin.org; a comment in the file suggests changing the warning to red 72 hours before the beginning of the potential chain split.  I will submit a PR for that on the 28th.
I will do my best to submit PRs with changes to the page on and after August 1st, although of course anyone else can submit a PR to Bitcoin.org too.
Preview:

Alerts: add warning for potential 2017-08-01 BIP148 split

---

_alerts/2017-07-12-potential-split.md

The split alert has a typo.
> spread those loses across
*losses*

Fix typo on split alert.

---

_alerts/2017-07-12-potential-split.md

Since the [alert](https://bitcoin.org/en/alert/2017-07-12-potential-split) went live last night, I've read a lot of feedback from people who are confused about what a chain split is and are asking others to ELI5 (explain like I'm 5).
This PR adds a brief, high level overview of what a chain split is to the beginning of the post. Unless there is any strong objection that anything I've said is fundamentally incorrect in describing a chain split, I will merge this today at 18:00 UTC.  Also, if anyone would like to suggest any improvements or additional copy, please feel free to submit a PR to my branch before then (`wbinns-split-updates-0713171`), or open a new PR or Issue later today.

Add explanation describing chain splits

---

en/rss/releases.rss

This change adds `description` content to releases rss feed.
Closes #1163
If this is accepted, please pay the bounty to 1BzwBwPfrm2fQRaTzuNSCTWeXnF3jmcL7G

Add description to releases rss feed

---

_alerts/2017-07-12-potential-split.md

It appears that many miners, perhaps 50% or more, "false signaled" for BIP91, meaning they set their versionbits manually without running either Core+BIP91 patch or Btc1.  If they continue doing this, this means that they may build on top of BIP91-invalid blocks on or after block 477120.  BIP91-compliant miners may then orphan those blocks.  Spy mining aggravates this situation.
This short update describes the minimal problem and response.  I've clicked the box to "allow edits from maintainers" so that @wbnns can make whatever edits he thinks are appropriate without him and I needing to argue about it.

Alerts: BIP148/91: update with post-91 disruption risk

---

_includes/references.md

Wiki page URL contained case error (bitcoin->Bitcoin)

Correct bcc configuration reference

---

.gitignore
.tx/config

This PR adds Transifex configuration to the project, so when the full project is developed locally, this can be done within a single repository/folder.
Having a configuration in the repository also can simplify the instructions for translators and make it easy to create scripts to automate some translations related tasks, like #1657.

Add Transifex config to the repository

---

.tx/config

This PR adds English language as a source in Transifex config, what is required when working with Transifex CLI to manually upload files.

Adds English language as a source in Transifex config

---

_includes/layout/base/wallets-list.html
_includes/layout/base/wallets-menu.html
_layouts/wallet-container.html
_plugins/wallets.rb

This PR fixes a problem when platform URLs have duplicated name.
```
https://bitcoin.org/en/wallets/web/web/ -> https://bitcoin.org/en/wallets/web/
https://bitcoin.org/en/wallets/hardware/hardware/ -> https://bitcoin.org/en/wallets/hardware/
```

Fixes an issue with URLs like /web/web/

---

docs/managing-wallets.md

This PR codifies what I believe to be our de facto criteria for the last two years.  There has been a fair amount of [discussion](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1109) et al. with very little support for listing wallets that do not allow access to private keys.  For over two years we have not listed any new wallets that do not allow access to private keys.  Instead, we have listed such submissions elsewhere on the site under other categories.

Require access to private keys for wallets 

---

_alerts/2017-07-12-potential-split.md

This removes the current alert as discussed in #1726 and will be merged once tests pass.
Closes #1726

alerts: Discontinue network disruption alert

---

_includes/devdoc/example_testing.md

When I ran the listed command, it took 100 ms on my laptop:
```
real	0m0.100s
user	0m0.001s
sys	0m0.003s
```
I don't know how my laptop compares to a "generic PC", but I don't think it's 10x faster, much less 300x faster.

update -regtest generate time

---

_includes/layout/base/head-menu.html
_templates/buy.html
_templates/getting-started.html
_translations/en.yml

This adds a 'Buy Bitcoin' page to Bitcoin.org. This page will allow us
to begin ranking and capturing traffic on search engines for the key
phrase 'buy bitcoin' which receives upwards of 100,000 unique searches a
month on Google, alone.
This strategy was employed with our Bitcoin Exchanges page, now the
fourth most-visited page on the site for the last three months. It has
received over 1,000,000 page views since it was added and is now also
the first search result on Google when the search term 'bitcoin
exchange' is used.
Unless others object, this will be merged on Tuesday, August 15th.
Screen shot:
Closes #1573

buy-bitcoin: Add 'Buy Bitcoin' page

---

_translations/en.yml

Could also be changed to "How to buy Bitcoin". "Buy - Bitcoin" just follows the structure of all other pages.

Fixed "buy bitcoin" title

---

_templates/exchanges.html

This removes BTCXIndia from the exchanges page. It appears they have
shifted away from BTC and are focusing solely on Ripple-related exchange
pairings, now.

exchanges: Remove BTCXIndia

---

_templates/exchanges.html

Quadriga has ~80% market share in Canada, seems a dis-service to newcomers to omit it from the list.

Add Quadriga CX canadian bitcoin exchange

---

_templates/exchanges.html

This removes BTCC from the Exchanges page. They announced that they
will be halting all trading as of September 30, 2017:
https://twitter.com/YourBTCC/status/908285586368167936

exchanges: Remove BTCC

---

_releases/v0.15.0.md

This fixes a small issue in the release notes where today's date is
accidentally referenced as October 14th, 2017.

v0.15.0: Fix incorrect reference to date

---

.travis.yml
Gemfile
Gemfile.lock

This PR upgrades Ruby version as well as some dependencies (json library) to improve stability and minimize a risk of future upgrades. The library upgrade is necessary due to incompatibility with Ruby version > 2.0.0.
Apart from that I noticed slightly reduced build time using a newer version.
As stated in the instructions I need to notify site maintainers, in this case I assume that's @wbnns, that `rvm install 2.4.1` also must be run on the build server before doing a merge.

Upgrades Ruby version in Gemfile and Travis config

---

_templates/exchanges.html

Bitsquare recent rebranded to "bisq" and now has a new website. The previous one (https://bitsquare.io) redirects to the new location, but this should not be counted on long term.

Update Bitsquare exchange branding

---

_includes/devdoc/guide_p2p_network.md

Cherry picking `f7d218d8d70febbfbde6c67ad4824571268d4eda` from #1740 so a first time contributor won't have to rebase due to a recent Gemfile update we made.
#1740:
```
BIP 130 added a new standard protocol for announcing new blocks that
is not yet documented in the Bitcoin Developer Guide.
```
This will be merged from once tests pass.
Cc: @jimpo

Document direct headers annoucement in block broadcasting guide.

---

_includes/devdoc/example_transactions.md

In this part https://bitcoin.org/en/developer-examples#p2sh-multisig
`spendtoaddress` should be `sendtoaddress`

Fix a typo in file _includes/devdoc/example_transactions.md

---

_releases/v0.15.0.1.md

Add Bitcoin Core 0.15.0.1.
There's only one bugfix in this release, that affects only GUI users. It was annoying enough to do a new build, though:
> After upgrade to 0.15.0, some clients would crash at startup because a custom
> fee setting was configured that no longer exists in the GUI. This is a minimal
> patch to avoid this issue from occuring.
I've kept the release notes the same as 0.15.0, updating the download link and adding mention of the fix.

Bitcoin Core 0.15.0.1

---

_includes/devdoc/example_p2p_networking.md

It seems that the word "computed" is repeated twice by mistake.

Remove repeated word "compute" by mistake

---

_includes/helpers/vars.md

Typo: timerecived -> timereceived

---

_templates/exchanges.html

Both companies will continue to list bitcoin as bitcoin:
[SurBTC](https://blog.surbtc.com/our-stance-on-the-segwit2x-hard-fork-9fd04323667b)
[BitOasis](https://www.reddit.com/r/Bitcoin/comments/75au0p/nya_signer_uae_company_bitoasis_wont_support_s2x/)

Re-add BitOasis, SurBTC

---

_includes/devdoc/bitcoin-core/rpcs/intro.md

Added in Bitcoin Core 0.14.0.
I was made aware of this during a discussion on IRC just now and had no idea these even existed (they're in the release nodes for 0.14.0).

Update rpcs/intro.md to explain use of named arguments

---

_includes/devdoc/ref_p2p_networking.md

Corrected information about protocol version number 106 to include
information added to the version message.
Corrected information about protocol version 209 to include the
verack message and additional fields added to the version message.

Corrections to protocol version numbers 106 and 209

---

_includes/devdoc/bitcoin-core/rpcs/rpcs/gettxout.md

See details: https://bitcoin.stackexchange.com/questions/48504/how-to-check-if-an-output-has-been-spent/48505?noredirect=1#comment70553_48505
>  It gives information about unspent outputs, and won't return anything for spent outputs.

Fix incorrect `GetTxOut` description

---

_events.yml

This removes events that have already passed from the [Events page](https://bitcoin.org/en/events), and also adds some new ones:
- Blockchain in Africa
- Blocktrain 1.0
- Blockchain West
- Blockchain Summit Kyiv

Update Events Page

---

_alerts/2017-10-09-segwit2x-safety.md

This drops the 2X alert that's currently displaying across the
tops of all pages on the website, [since there will no longer be a
2X-related fork](https://lists.linuxfoundation.org/pipermail/bitcoin-segwit2x/2017-November/000685.html).
Unless others object, this will be merged on Sunday, November 12th.

_alerts: Drop 2X alert from tops of pages

---

_posts/2017-10-05-denounce-segwit2x.md
_templates/exchanges.html

We have not defaulted tickers to Segwit2x. More info in our blog: https://blog.bitso.com/planes-para-el-segwit2x-bitcoin-hard-fork-e347117298e8

adding Bitso to bitcoin.org

---

_templates/about-us.html

Some people are still contacting me due to this page although I am now uninvolved since a while.
And as for the credits, I still show up in the list of contributors from GitHub, which is all fine by me.

Remove Saivann as the inactive website maintainer

---

_templates/exchanges.html

Independent Reserve has been operating since 2013 and is one of the leading exchanges in Australia and New Zealand

Updated exchanges.html to add Australian and New Zealand exchange

---

_wallets/bitgo.md

This fixes an issue with some broken links (#2018) as a result of the
BitGo Chrome App being discontinued, and will be merged once tests pass.
Closes #2018

_wallets: Update BitGo platform availability

---

_templates/resources.html

CriptoNoticias is the most read digital newspaper about Bitcoin in Spanish since 2015. We have over 1 million views per month with exclusive news about Latinamerica and Spain and other significant topics related to cryptocurrencies.

Added news source in Spanish

---

.mailmap

This commit adds a .mailmap file as described in the `git shortlog`
manpage, normalizing names and email addresses for several top
committers.
For context, see the conversation between @cbeams and @harding at
https://twitter.com/cbeams/status/967491714335297536. Entries in a
.mailmap like those found in this commit eliminate the need to manually
"combine multiple entries" for authors like @wbinns who have had commits
with varying author metadata over time.
Ultimately, the purpose is to make the output of `git shortlog` as
concise and accurate as possible. Compare the results of `git shortlog
-nse` before and after this commit to see the difference it makes.

Add .mailmap with entries for top committers

---

_includes/templates/index.html
_translations/en.yml

Reverts bitcoin-dot-org/bitcoin.org#2010
This reverts the referenced pull request and restores the mention of the "Fast peer-to-peer transactions", "Worldwide payments" and "Low processing fees" features that were previously highlighted in the homepage. At the time the pull request was created, the fees were temporarily high, and there was little adoption of Segwit and batching. Since then, the fees have been low.
There was also not enough thought put into the original pull request, since it's still showing the old labels for languages other than English. I propose we comprehensively change the text across all languages when the fees are very high on a **permanent** basis, which I think is some years off thanks the ecosystem taking better care to optimize usage of the blockchain.

Revert "update network descriptions to be more accurate"

---

_posts/2018-05-01-test-the-new-site-design.md

This adds a new blog post, soliciting testers from the community to help review the new Bitcoin.org design in preparation for launch.
Screenshot of post:
Cc: @Cobra-Bitcoin

blog: Add 'Test New Bitcoin.org Design' post

---

_data/devdocs/en/guides/transactions.md
_includes/references.md

Cleared up the confusion stemming from the outdated information in the P2SH documentation as described in #1894 . Since Bitcoin Core 0.9.2 , any valid redeemScript can be used aside from the P2SH pubkey script itself to prevent recursion, greatly extending the possibilities of P2SH. Also added a link to a python example from Peter Todd, a bitcoin core developer, showing how to store some text data on the blockchain using P2SH.
**Bounty / Donation Address**
BTC: `1NooxLZWSw4h7eUhxkEf3PMRxd2WFEqhwp`

Improved the P2SH documentation

---

_templates/exchanges.html

https://www.coinspot.com.au/ is a reliable and popular Australian exchange I've used several times to buy Bitcoin and Altcoins. I am not affiliated with them in any way.

Added CoinSpot to Australian Exchanges

---

_data/devdocs/en/bitcoin-core/rpcs/rpcs/getinfo.md

as from output
```
>bitcoin-cli -datadir=regtest -regtest help getinfo
error code: -32601
error message:
getinfo
This call was removed in version 0.16.0. Use the appropriate fields from:
- getblockchaininfo: blocks, difficulty, chain
- getnetworkinfo: version, protocolversion, timeoffset, connections, proxy, relayfee, warnings
- getwalletinfo: balance, keypoololdest, keypoolsize, paytxfee, unlocked_until, walletversion
bitcoin-cli has the option -getinfo to collect and format these in the old format.
```

GetInfo was removed in 0.16.0

---

en/full-node.md

This resolves #2268 and will be merged once tests pass.

full-node: Remove '-daemon' param for Windows instrux

---

_data/devdocs/en/guides/block_chain.md

Changing a transaction has no impact on previous blocks, it only impacts the block on which the transaction occurs and the subsequent/following blocks.

Corrected a following to subsequent

---

_templates/resources.html

This drops Airbitz from the resources page as a place to go to find Merchants. The link was pointing to their homepage which doesn't appear to contain any relevant information.
It was originally added to the page back in 2015 (8308d27c2a32982b67ae7d0db529376b3f26f4c0), so perhaps their homepage has changed quite a bit since then and shifted direction.
Unless others object, this will be merged on Wednesday, May 23rd.

resources: Drop Airbitz as a 'Merchant' link

---

_wallets/coinspace.md
_wallets/digitalbitbox.md
_wallets/keepkey.md
_wallets/ledgernanos.md

This PR is to update the transparency score on coinspace @nikashitsa, digitalbitbox @douglasbakkum, keepkey @dstanchfield, and ledgernanos @EricLarch wallets.  These wallets had previously been listed  as "new" wallets which which earn the "fail" scoring.  These wallets have now all been listed for over six months and deserve better scoring.  Often, we allow developers to propose their scoring, but since these are overdue, I'll propose updated scoring here.

Update transparency score on mature wallets

---

_layouts/about-sidebar.html

This fixes a typo ('begining') and will be merged once tests passed.

about-sidebar: Fix typo, 'begining'

---

_alerts/2016-11-01-alert-retirement.md

On https://bitcoin.org/en/alert/2016-11-01-alert-retirement#the-retirement-plan , the markdown-table is broken by the div added to the end of it:
This should fix it.  Note, I only tested with a quick preview not a full site build.
This is related to the links being added in https://github.com/bitcoin-core/bitcoincore.org/pull/567

Alerts: Bitcoin Network Alert Retirement: Fix broken table

---

_templates/exchanges.html

We are a brazilian startup that seeks compliance in crypto currency trades. We can issue invoices to our services to enable the trade of crypto currencies. We also integrate digital bank accounts speeding up operations with FIAT;
__Unfortunately we don't own the *.com* domain.__
- 3xbit.com.br
- 3xbit.exchange
- 3xbit.global
- threexbit.com
- threexbit.com.br
- https://www.crunchbase.com/organization/3xbit
- https://startse.com/in/3xbit
- https://startupbase.abstartups.com.br/startup/1898
- http://facebook.com/3xbit.global
- http://twitter.com/3xbit
- http://linkedin.com/company/3xbit
- http://instagram.com/3xbit.global

Adds 3xbit to the List of Brazilian Exchanges

---

_alerts/2016-11-01-alert-retirement.md
_posts/2018-07-03-alert-key-and-vulnerabilities-disclosure.md

Blog post with the alert keys and vulnerabilities disclosure from https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-July/016189.html.
Adding this to Bitcoin.org as a more permanent place to have the alert keys than just a mailing list's archive.

Alert key disclosure and vulnerabilities blog post

---

_wallets/greenaddress.md

-  greenaddress web use was already discouraged, now deprecated
-  google deprecated chrome apps, greenaddress chrome app replaced by desktop app
Also updates from checkfailtransparencyremote to checkpasstransparencyopensource - the argument was that people wouldn't use the chrome app with web, but both web and chrome app are deprecated and the app is not loaded remotely.

update to replaced Desktop app, deprecate web

---

_sass/screen.scss
_templates/exchanges.html
_translations/en.yml

This adds a new P2P category on the exchanges page, to help highlight and support exchanges that are based on P2P exchange:
The P2P directory card on the buy bitcoin page will also be linking to this.
This is scheduled to be merged on Monday, July 16th.

Add P2P section on Exchanges page

---

_templates/community.html

The #bitcoin-dev IRC channel has been dead for more than two years now, so this updates the text to point to the active #bitcoin-core-dev channel.

Update IRC channel: #bitcoin-dev → #bitcoin-core-dev

---

_wallets/bither.md

It seems that Bither for iOS [may no longer be available](https://itunes.apple.com/us/app/bither/id899478936) in the App Store. This drops the iOS option so users don't get misdirected to it.
Reached out to Bither Support to confirm (or perhaps others are able to load the page and it is some sort of localized or regional problem with the App Store). Will wait before merging just in case.

bither: Remove Bither for iOS

---

docs/managing-wallets.md

I propose moving the deterministic nonce wallet criteria from optional to required.
It's just a good idea.  The only downside I've ever heard expressed is a 10% performance hit.  In the past three years all new wallets listed on bitcoin.org have signed with deterministic nonces.

Move deterministic nonce wallet criteria from optional to required

---

_templates/exchanges.html

This PR makes a couple small fixes to the Exchanges page and will be merged once tests pass:
1. Fixed the Polish flag icon which erroneously had an alt tag listing it as the flag for the United Kingdom (when doing this I also checked to make sure the names of the flags were standardized).
2. Removed several unnecessary line breaks.

Small exchange page fixes

---

_templates/exchanges.html

I went through the exchanges on the Exchanges page and recommend we remove some listings:
- [Bitcoin Cambodia](https://bitcoincambodia.com/) - This exchange is no longer accepting new user registrations.
- [Bitaccess](https://bitaccess.ca/) - Their Buy/Sell button redirects to [another site](https://buybitcoincanada.com/) which was showing the current exchange rate of BTC/CAD as $9164.75 ($6993.01 USD) - this was off by almost a thousand dollars. Revisiting this page approximately 12 hours later, the price was unchanged - it was exactly the same. It seems they are providing an unreliable exchange rate.
- [OKCoin.cn](https://okcoin.cn/) - While it's possible to sign up, it does not seem possible to trade BTC/CNY. There are also no other exchange rates listed. It seems to be more-so of a …

Exchange Page Maintenance

---

_wallets/bither.md

This Pull Request reverses #2530. After the discussion in #2530 with @wbnns , Apple eventually finished their review of Bither app. Bither is now back in App Store. 
[This link](https://itunes.apple.com/us/app/bither/id899478936) can lead you to the App Store download page of Bither when opened on iPhone.
Thank you for your effort @wbnns . Now we can add Bither iOS back.

Add Bither for iOS Back

---

_data/devdocs/en/bitcoin-core/rpcs/rpcs/getblock.md

This pull request is an updated documentation proposal for the open issue #2251. This is an improved documentation of the second parameter of getBlock (verbosity).
1 - Document the backward compatibility change of verbosity level from Boolean to integer. 
2 - State the version in which the change occurred.
3 - Remove the Boolean examples and added the new integer examples.
4 - Since the information result for verbose level 1 and 2 are very similar except for "tx", I took the same data and updated the "tx" field with the relevant information.
18mutz7tyhq2F1dN7593dbKUep3ZFEiZcV

GetBlock documentation update required for the verbosity parameter.

---

_data/devdocs/en/bitcoin-core/rpcs/quick-reference.md

PR to add deprecated for 'estimatefee' as requested in #2219

Fix for #2219: Add deprecated to Estimate Fee in developer reference

---

_includes/layout/base/wallets-filter.html
_includes/layout/base/wallets-list.html

This fixes https://github.com/bitcoin-dot-org/bitcoin.org/issues/2585 and hides the currently selected wallet because it's redundant to display it.

Hide currently selected wallet

---

_templates/resources.html

The documentary links currently available in the site are dated back 2014-2015. This PR updates three more recent (2017) documentary links.

[Resources] Add more recent Bitcoin Documentary links

---

_templates/about-us.html

This updates Pavle Djordjevic's position as the Serbian translation coordinator to use his real name instead of his alias ([as discussed](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2596#issuecomment-414570070) in #2596).

about-us: Change alias to real name

---

_includes/templates/index.html
_posts/2018-08-16-ten-year-anniversary.md
_sass/screen.scss

Tomorrow, August 18, 2018 will be ten years since the bitcoin.org domain was registered. This PR adds  a blog post commemorating the milestone and thanks the contributors who have helped develop the site over the years:
I added a small link on the homepage (that only appears to English readers), linking to the blog post and was thinking we could leave it up for the next week or so (if people think it's a good idea):
Feedback welcome.
Cc: @Cobra-Bitcoin
Closes #2294

Add 10 Year Anniversary of Bitcoin.org Blog Post

---

_includes/templates/index.html

This shortens the announcement text in #2597 so that it won't wrap on smaller mobile / handheld devices, and will be merged once tests pass.

index: Shorten text to remove wrap

---

_templates/scams.html
_translations/en.yml

This page inherited an issue from the glossary page that it was modeled after, where-in a translation string was missing. This fixes the issue and also provides the applicable string for the page.

scams: Add translation string

---

_layouts/sidebar.html

This fixes an issue where-in some pages inherit button text from sidebar.html that does not make sense - like on the exchanges page, for example, where it says 'View Topics'. There are no topics on that page. This is because the table of contents button in the sidebar was erroneously written for the vocabulary page. As implemented, it should have been more generically worded. This updates the text to say 'View All' instead so that it makes sense when displayed on different pages.
This affects mobile / handheld device users and will be merged once tests pass.

sidebar: Change 'View Topics' to 'View All'

---

_templates/exchanges.html

Bitcoin Indonesia has rebranded and changed their name to Indodax. This
updates the name and will be merged once tests pass.

exchanges: Change name, Bitcoin Indonesia > Indodax

---

_includes/templates/index.html

This drops the blog post link on the homepage that Bitcoin.org is 10 years old, which has been up for the past week, and will be merged once tests pass.
Related: #2597

index: Drop Bitcoin.org Anniversary Note

---

_templates/exchanges.html

Argenbtc.com is one of the oldest exchange in Argentina with almost 5 years online.

Add oldest argentinian exchange

---

docs/assisting-with-translations.md

This PR adds the sections "Getting started with the Translation Team" and "Responsibilities and Tasks for each User Role" to the "Assisting with Translations" document, while the original content of the doc is slightly changed and now serves as section "Handling Translations on GitHub".
@wbnns there you go :)

Extended "Assisting with Translations" document

---

_data/devdocs/en/guides/block_chain.md

Seemingly is an adverb and thus doesn't need a hyphen.

Remove unnecessary hyphens

---

_data/devdocs/en/guides/contracts.md

"part-time" does not need to be hyphenated in this sentence. Examples:
She held a part-time job.
She worked part time on the forum.

Remove unnecessary hyphen

---

_data/devdocs/en/guides/payment_processing.md

Adverbs, which end in -ly, do not need hyphens. I am continuing onward with my documentation review and testing.

Add minor spelling fixes

---

docs/assisting-with-translations.md

This adds a small note regarding background experience that would be helpful in order to update translation files on Bitcoin.org. There was some confusion in not realizing one needed to know a bit about how the stack operates as a prerequisite. This also adds Hendrawan, a Team Leader on Transifex, as a person who can be contacted for translation-specific questions (in addition to Simon).

docs: Add note mentioning Hendrawan and background exp. for handling translations

---

_includes/layout/base/html-head.html

This imports main.js into the download page so we can call the function to show the donation modal, which currently isn't displaying.
I screwed up in https://github.com/bitcoin-dot-org/bitcoin.org/pull/2626 a bit, but this fixes that. Suggest to merge as soon as tests pass.

Show donation modal in download page

---

_sass/screen.scss

Scroll bar would show after the table of contents snapped to bottom, namely on phones in portrait mode. The extra padding seemed to be causing this. That padding is not longer needed once the TOC is at the bottom.

Fix for overflow-x scrolling on mobile phones

---

_alerts/2018-09-21-required-upgrade.md

This PR is based on [additional feedback](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2666#issuecomment-423424702) and makes the following changes to the 0.16.3 upgrade notice:
+ Fixes a typo in the second to last paragraph of the alert
+ Makes some additional simplifications to the text
+ Drops link to reddit and links to GPG, release signatures and signing key
+ Consolidates download links to bitcoin.org/en/download
+ Adds emphasis (bold) to indicate stored funds are not at risk and links to value overflow incident
This is scheduled to be merged on Sunday, September 23rd (48 hours).

_alerts: Additional cleanup of new alert message

---

_data/devdocs/en/bitcoin-core/rpcs/rpcs/signrawtransaction.md

Mark that signrawtransaction is deprecated (it's scheduled for removal in 0.18.0).

Add deprecated to signrawtransaction

---

_includes/templates/index.html

This drops the 0.16.3 upgrade alert notice from the homepage.
It has been up for the last couple of weeks.

index: Drop 0.16.3 Upgrade Alert Notice from Homepage

---

_includes/templates/index.html
_sass/screen.scss
_templates/buy.html
_translations/en.yml

The Paxful sponsorship ends on October 11th. There are currently no plans or discussions to renew it, so this PR is scheduled to be merged on that date.
We were hoping there might be an opportunity to have more of a long-term relationship with them, however, at present, we feel it may not be in the best interest of trying to represent differing perspectives if we renew the sponsorship. That said, we hope there will be more opportunities for sponsorships on the site in the future. Bitcoin.org is one of the only leading/most-visited websites in the space that isn't directly or indirectly fueled by companies seeking to unilaterally press their own for-profit initiatives. 
We thank Paxful for their support.

 buy: Non-renewal of Paxful Sponsorship

---

_templates/exchanges.html

This closes #2577 as part of the discussion that was had regarding reconsideration of the site ban on NYA companies. I did not add Xapo back to the Exchanges page because I've seen a number of people mentioning issues with their KYC/AML process (e.g. long delays, no response to questions) and/or lack of responses from their support team. I also logged into a web wallet to ask their support team if it's possible to buy/sell bitcoin with them to confirm and never received a reply.

exchanges: Add back NYA agreement companies

---

_templates/community.html

This removes a dead link pointing to "Fundacion Bitcoin Colombia" on the
Community page and will be merged once tests pass. The referenced domain
(bitcoincolombia.org) only shows a default cPanel configuration page,
now.
Cc: @santy2001

community: Remove Colombian Nonprofit

---

_data/devdocs/en/examples/payment_processing.md
_data/devdocs/en/guides/payment_processing.md
_data/devdocs/en/guides/transactions.md
_data/devdocs/en/references/p2p_networking.md
_data/glossary/en/payment-protocol.yaml

BIP70 has been [deprecated](https://github.com/bitcoin/bitcoin/pull/14451) in Bitcoin Core and its use should be strongly discouraged due to design and implementation flaws that have an impact on security.

Add BIP70 deprecation warnings

---

js/cookieconsent/light-floating.css

On IE for desktop resolutions, the cookie consent pop-up is displayed on the left side of the screen with no space to the left:
as opposed to being displayed on the right side of the screen, like on Chrome, Firefox, Opera:
By changing the value of the "left" property on that element from "initial" to "auto" it will be displayed correctly.
This is happening because IE does not support the "initial" value:
https://caniuse.com/css-initial-value
Also, "auto" **is** the initial default value for the "left" property.

Resolves IE positioning issue of cookie consent popup.

---

_templates/community.html

This closes #2769 and drops "The Bitcoin Alliance of Canada" from the community page. This will be merged once tests pass. The link that is being removed is redirecting to an alternative blockchain / token-based initiative, with no specific relation to Bitcoin.

community: Drop Bitcoin Alliance of Canada

---

_templates/resources.html

This drops BitcoinFilm.org from the Resources page and will be merged
once tests pass. Their site has been showing a PHP error and hasn't been
loading properly for a couple of weeks, now:

resources: Drop 'BitcoinFilm.org'

---

_templates/exchanges.html

This drops Bitmae from the Exchanges page and will be merged once tests
pass; they are redirecting to Xapo.

exchanges: Drop Bitmae

---

_templates/exchanges.html

This drops QuickBT from the exchanges page and will be merged once tests
pass. They ceased operations as of this past week.

exchanges: Drop QuickBT

---

_templates/community.html

This drops the Belgian Bitcoin Association from the community page and
will be merged once tests pass. Their domain expired on December 24th
and the website no longer resolves.
Cc: @arnuschky

community: Drop 'Belgian Bitcoin Association'

---

_templates/community.html

Checked all links were still working. Removed one url that now redirects to an ATM manufacturer.
Changed to https:// where possible.

Community page housekeeping | http -> https

---

Makefile

As mentioned by @crwatkins on https://github.com/bitcoin-dot-org/bitcoin.org/pull/2840#issuecomment-460851781 , the schema-validation test failed to catch a problem.  This appears to have been because of how the test was modified to run as a child of the `find` process.  `find` always returns true if it finds files, so its child processes failures wouldn't be propagated back up to the test process.  This fixes the oversight.
I've tested this by reintroducing the exact problem identified by Craig above, running the test, and ensuring that it raised a fault.  Upon removing the bug, the test passes.

Tests: fix wallet schema test

---

_wallets/electrum.md

As suspected in #2837 Electrum on Android seems to support Tor (tested using Orbot).
@ecdsa unless you let us know otherwise, this closes #2837.
Thanks @JeremyRand.

Update Tor support for Electrum on Android

---

_includes/layout/base/head-logo.html
img/icons/logotop.svg

Replaces the logo on the head of the site with SVG version, which sharpens and improves the quality of the logo considerably on higher resolution displays.

Update to using SVG logo

---

_templates/community.html

This removes the [Bitcoin Organization of the Philippines](https://bitcoin.org.ph/) from the
Community page and will be merged once tests pass. Their site has been
going up and down over the past month, and has now been down for seven
days straight, it seems.
This is to protect our [page rank](https://en.wikipedia.org/wiki/PageRank) from being harmed by linking to web
pages (like this one) that 404 and/or domains that do not respond. When
a page on the site does this, search engines can in turn give our
corresponding linking page a lower search engine ranking, because they
will deem that the page has less relevancy for the search phrase, since it
links to content that doesn't exist (compared to other web pages on
other web sites that could be competing in the search results against
us, …

community: Remove Bitcoin Organization of the Philippines

---

_data/devdocs/en/references/p2p_networking.md

There are already 7 type identifier defined not 3.

Fix number of allowed Inv. message type identifier

---

_data/devdocs/en/references/intro.md

As we are on 0.17 now, text updated to represent what has been already developed rather than tasks going to be developed

Changed verbal tense to reflect currently provided consensus sharing from v 0.10.

---

_wallets/wasabi.md

Wasabi wallet's transparency score was added with `checkpasstransparencyopensource`. This PR updates its to `checkgoodtransparencydeterministic`.
The reason for `checkpasstransparencyopensource` is that I was not familiar with the deterministic builds concept at the time, thus I just opened an issue to research it: https://github.com/zkSNACKs/WalletWasabi/issues/1078 
I've done my investigation now and it turns out, our tooling is creating deterministic builds by default. While I went ahead and verified it, of which the rest of this comment is about, I'd like to note that in the commit https://github.com/zkSNACKs/WalletWasabi/commit/b4c86c83b978ab0a8ea1fbf2354ec41447634d4d I explicitly specified the deterministic compiler flag to make it future proof and to avoid relying on the default …

Change Wasabi transparency to checkgoodtransparencydeterministic

---

_config.yml

'한국의' means 'of Korea'.
The correct translate of 'Korean' is '한국어'.

Fix Wrong Language Name

---

_data/devdocs/en/guides/transactions.md

Add a complete list of standard transaction types after the introductory paragraph. 
Resolves issue #2918

Add list of standard transaction types

---

_data/devdocs/en/bitcoin-core/rpcs/rpcs/verifymessage.md

It's not true that all four possible public keys (corresponding to recovery
ids) are tried. The recovery id is instead read from the signature, see
https://github.com/bitcoin/bitcoin/blob/78dae8caccd82cfbfd76557f1fb7d7557c7b5edb/src/pubkey.cpp#L189.

Remove incorrect explanation of `verifymessage`

---

_templates/community.html
_translations/ar.yml
_translations/bg.yml
_translations/da.yml
_translations/de.yml
_translations/el.yml
_translations/en.yml
_translations/es.yml
_translations/fa.yml
_translations/fr.yml
_translations/hi.yml
_translations/hu.yml
_translations/id.yml
_translations/it.yml
_translations/ja.yml
_translations/ko.yml
_translations/nl.yml
_translations/pl.yml
_translations/pt_BR.yml
_translations/ro.yml
_translations/ru.yml
_translations/sl.yml
_translations/sr.yml
_translations/sv.yml
_translations/tr.yml
_translations/uk.yml
_translations/zh_CN.yml
_translations/zh_TW.yml

This drops the Google+ Bitcoin Community link from the [Community](https://bitcoin.org/en/community) page and will be merged once tests pass. Google recently officially shutdown Google+ this month. The link on the Community page now leads to a notice regarding the shutdown:

Drop Google+ Bitcoin Community from Community Page

---

_templates/community.html

This drops Dansk Bitcoinforening from the community page and will be
merged once tests pass. The site has been returning a 404 for many days.

community: Drop 'Dansk Bitcoinforening'

---

en/full-node.md

This fixes a broken link in the 'Running a Full Node' instructions and
will be merged once tests pass.

full-node: Fix broken link to Upstart script

---

_templates/resources.html

This updates the link to TradeBlock so that it points to the bitcoin
section of their site instead of their homepage. Their homepage loads a
generic page about enterprise tools for blockchain assets.

resources: Update TradeBlock link

---

_translations/es.yml

Se remueve texto y enlace que daban acceso a la descarga del archivo bootstrap.dat (copia anterior de la cadena de bloques) por no estar disponible.

Removidos los enlaces no disponibles

---

_templates/community.html

This adds the Chilean Bitcoin Association to the community page and is
scheduled to be merged on Friday, April 26th (if there is no objection).

community: Add Asociación Bitcoin Chile

---

Makefile
_sass/screen.scss
_templates/download.html

- Fixes broken test that allowed #2945 to be merged as passing
- Removes broken links (similar to @MarcoFalke's #2946, but also including JS changes.  Sorry, I didn't see your PR until I finished testing mine.)
- Adjusts style on download page so that the Windows box isn't 2x as high as other platforms even though it now only has one line, e.g.:

Fix broken links on Download page

---

.travis.yml

Builds in sudo-disabled docker containers are no longer available as of last year and all builds happen on sudo enabled vms.
Source: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration#timeline---its-happening-fast

Remove sudo:false from travis.yml

---

_data/devdocs/en/bitcoin-core/rpcs/rpcs/getdifficulty.md
_data/devdocs/en/bitcoin-core/rpcs/rpcs/verifychain.md
_data/devdocs/en/guides/mining.md
_translations/en.yml

This fixes at typo in one of the English strings where "Confirmations"
is misspelled as "Confirm&shy;ations", and will be merged once tests
pass.

en: Fix typos

---

_sass/screen.scss

This resolves an issue where link colors weren't correctly styled (they should be blue, to match the other links they reside with in the center content area) on the Community and Exchange pages, and will be merged once tests pass --
**Before:**
**After:**

Fix link styling on Community and Exchange pages

---

_templates/community.html

This adds the [Bitcoin Association of Northern Ireland](https://www.bani.org.uk/) to the [Community page](https://bitcoin.org/en/community) and is scheduled to be merged on Friday, May 10 (unless others object).

community: Add 'Bitcoin Association of Northern Ireland'

---

_sass/_wallets-menu.scss

This resolves an issue in the wallet selector for mobile / handheld devices where the `capitalize` value for the `text-transform` property in the `selected-item` class doesn't play nice with words that follow a non-standard convention for capitalization (e.g. iOS):
The value has been changed to `uppercase` in order to standardize the appearance of the form fields, above, once selected:
This is scheduled to be merged on Friday, May 10 (unless others object).

wallets-menu: Upcase selected item

---

_data/devdocs/en/bitcoin-core/rpcs/quick-reference.md

EstimateFee block currently reads:
EstimateFee: estimates the transaction fee per kilobyte that needs to be paid for a transaction to be included within a certain number of blocks. Updated in 0.14.0Deprecated
There should be a space between the updated tag and deprecated tag.

Added a space for EstimateFee deprecation warning.

---

_templates/community.html

This drops the Bitcoin Foundation of Ukraine from the Community page and will be merged once tests pass. The website is no longer available:
Cc: @khendraw

community: Drop 'Bitcoin Foundation Ukraine'

---

_posts/2018-09-14-how-to-translate.md
docs/assisting-with-translations.md

This updates the link to the Telegram group which was referenced in
several places and is used by some of the members of the translation
team for bitcoin.org - the previous link has expired.

translations: Update link to Telegram group for site translators

---

_templates/exchanges.html

This drops bitFlyer's Japanese site from the list of exchanges in Japan and will be merged once tests pass. They are no longer accepting new user registrations due to issues with regulators.

exchanges: Drop 'bitFlyer' from Japanese exchanges

---

_templates/exchanges.html

This drops iCE3X from the list of South African exchanges:
+ The footer of the website appears to be broken and is missing links to things such as their Terms of Service, Privacy Policy and Support pages when a user isn't logged in.
+ The Help link in the header of the site doesn't appear to be loading and redirects to a login page.
+ We reset our password on an existing account but did not receive a temporary password along with reset instructions.
+ When creating a new account, all emails received that were pertaining to the new account went to Spam.
+ The exchange doesn't have any SPF records configured for the primary domain that emails are sent on behalf of which will cause emails sent on behalf of the company to go to spam, and also make it easier for others to spoof the exchange in …

exchanges: Drop 'iCE3X' from South African exchanges

---

_templates/exchanges.html

This drops [Bitcoin Australia](https://bitcoin.com.au/) from the Exchanges page and will be merged once tests pass. Upon additional review, we discovered that this website maintains almost an identical content-based layout as two websites that were not added to the Exchanges page in #2949:
+ [bitcoin.co.uk](https://bitcoin.co.uk/)
+ [bitcoin.ca](https://bitcoin.ca)
Searching for 'The Trusted Cryptocurrency Exchange' - an excerpt of the title tag that all of these websites share - revealed two more sites that also share the same/similar content, metadata and layout:
+ [bitcoin.eu](https://bitcoin.eu)
+ [bitcoin.com.tr](https://bitcoin.com.tr)
At some point Google will drop all of these sites from their index because they are all sharing similar/duplicate content. Ensuring they are not …

exchanges: Drop 'Bitcoin Australia'

---

_includes/templates/index.html

This resolves an issue on the home page where the phrase "What is Bitcoin?" that was appearing next to the video play button wasn't getting translated, and will be merged once tests pass.
**Before:**
**After:**

index: Fix missing translation on homepage - 'What is Bitcoin?'

---

_templates/exchanges.html

This drops CoinLoft from the Australian section of the Exchanges page and will be merged once tests pass. Their price to buy bitcoin is ~7% higher than the market average. Their price to sell bitcoin is ~2.5% lower than the market average, which is also being advertised as a no commission trade. We have been observing this over the past week, before the recent bitcoin price up-swings, and contacted the exchange who confirmed that the rates are correctly advertised.
If a user were to use this exchange to buy bitcoin, the price of bitcoin would need to increase ~9.5% from the price they bought at just for the user to be able to break even if they were going to subsequently sell their bitcoin back to this exchange at some point in the future.

exchanges: Drop 'CoinLoft'

---

_templates/exchanges.html

This drops Luno from the list of exchanges in Singapore and will be merged once tests pass. They continue to be listed under other countries (Malaysia, Nigeria, South Africa), however, Singapore is no longer in the list of countries they support, [as per their website](https://www.luno.com/en/countries/).

exchanges: Drop Luno from Singapore

---

_data/devdocs/en/references/transactions.md

Per bitcoin source code, the transaction version is of type `int32_t`. Documentation currently lists it as a `uint32_t`.
bitcoin source: https://github.com/bitcoin/bitcoin/blob/c65c77c721b69f1782509145d62978d31c9a1d78/src/primitives/transaction.h#L289

Reflect correct transaction version type

---

_templates/exchanges.html

This removes Bit2C from the exchanges page and will be merged once tests pass. Their site is down and it appears their service has been discontinued.

exchanges: Remove Bit2C

---

_templates/exchanges.html

bitFlyer(JP, US, EU) has restarted accepting new user since July 2019.
https://twitter.com/bitFlyer/status/1146216150230917121
> 2019-07-03
> We would like to announce that new account creation has resumed. We sincerely apologize for the inconvenience incurred by anyone considering becoming a new customer of our services during this time.

exchanges: Re-add bitFlyer (JP, EU)

---

docs/managing-wallets.md

Currently we provide no guidance for developers submitting wallet descriptions for listing and recently we have been getting descriptions that seem too long.  Without some limit, we will have descriptions that don't currently lay out well, or may not lay out well in the future.  Also, longer descriptions are obviously more verbose and are likely not in the style of the other descriptions.  Currently we have no descriptions longer than 320 characters which I propose as our limit (arbitrary sum of two powers of two).
@natiwa @alexcherman Any thoughts on the layout considerations?
When this is merged, perhaps we could ask @harding to update the schema checker.

Add guidance for wallet descriptions

---

Makefile

Per #3048, this automatically tests the length of wallet descriptions (English only) and errors if any are over 320 characters.
When I first mentioned to @crwatkins that this could go in the schema, I had forgotten that wallet descriptions are stored in the translation file, so this is implemented differently than originally envisaged and it's dependent on the site continuing to use the existing naming scheme of wallet descriptions in the translation file starting with `wallet<walletname>`.

Tests: ensure wallet description lengths are under 320 chars

---

_data/devdocs/en/references/p2p_networking.md

Clarify the note about the relay field to include a description of the exact issue with the incompatibility with older protocol versions as discussed in issue https://github.com/bitcoin-dot-org/bitcoin.org/issues/1341

Clarify note about relay field

---

_build/update_torrent.sh

The following trackers are dead:
* `publicbt.com`: unreachable, since at least 2016: https://gist.github.com/mcandre/eab4166938ed4205bef4#gistcomment-1687275 
* `tracker.ccc.de:80`: same as above
* `open.demonii.com:1337`: unreachable, permanently closed in 2015: https://torrents.io/site/demonii
I tested that the other trackers still work as of today.
See also #1141 (@laanwj).
Not included in this PR, if people are interested, I setup my own tracker at `udp://tracker.bitcoin.sprovoost.nl:6969`. It's whitelisted, so shouldn't suffer the same fate as these folks: https://torrentfreak.com/running-a-torrent-tracker-for-fun-can-be-a-headache-160828/
Currently it tracks the 0.18.1 and 0.17.1 release torrents. I'm happy to keep whitelisting new releases.

Remove disappeared torrent trackers

---

_data/devdocs/en/examples/testing.md

The command `generate` is deprecated from Bitcoin Core 18.0. This PR adds the workaround proposed in the PR that deprecated it (https://github.com/bitcoin/bitcoin/issues/14299#issuecomment-424138977).

Update regtest block generation command

---

_translations/en.yml

We've noted that for the [Choose your wallet](https://bitcoin.org/en/choose-your-wallet) landing page, a meta description is missing. Meta descriptions are the text that search engines generally display alongside web page search results; it is the text that describes the web page. If this text is missing, a search engine will automatically try to extract copy from the page in order to present an accurate description of the page alongside the search result.
In the case of the choose your wallet page, while the search result on Google is acceptable, DuckDuckGo is erroneously extracting the wallet feature description for "2FA" and listing it as the search engine result description:
This adds the missing meta-description, along with a correct description, so that it displays properly across …

en: Add missing meta description to Wallet wizard

---

docs/managing-wallets.md

This adds some additional guidance to help wallet listing contributors choose the correct features to list for a wallet.  I believe that all current wallets adhere to these guidelines for feature selection, however these restrictions and allowances may or may not have been discussed here in the past, so review is encouraged and comments are welcome.

Add guidance for wallet features

---

_includes/layout/base/helper-step-3.html
_includes/layout/base/helper-step-4.html
_translations/en.yml

This adds a note under the Criteria and Feature selection portions in the new wallet selection wizard, so that people know they don't have to select criteria or features that are important to them, if they don't want to. This also covers a use case where people might not necessarily be sure which criteria or features are important to them.
__Desktop__:
__Tablet__:
__Handheld__:

Add optional indicator to wallet selection wizard

---

docs/managing-wallets.md

A bug reporting method is currently an optional criterion.  This PR makes it required.
All listed wallets have bug reporting methods.
(Another criterion was moved in the list to group similar criteria.)

Require bug reporting method

---

_templates/bitcoin-paper.html

This PR makes a technical clarification / change to the listing for the
Norsk translation of the Bitcoin paper, renaming the reference to "Norsk
(Bokmål)" instead of just "Bokmål". This is because "Bokmål" is the type
of Norwegian it's written on, not the language itself.
Cc: @sandwes

bitcoin-paper: s/Bokmal/Norsk (Bokmal)

---

_sass/_wallet-selector.scss

This ensures that the wallet name that appears in the wallet selector
results table, which is an active link, isn't overridden to appear as
black text, potentially making it more difficult to discern as something
that can be clicked on or touched to navigate to an individual wallet's
landing page:
Cc: @crwatkins

wallet-selector: Do not override anchor link style

---

_posts/2019-09-26-recognizing-efforts-contributors-to-translation-team.md

Thanks to continued donations and support from the community, we've recently been able to send out over $15,000 USD worth of bitcoin as a gesture of appreciation to people who volunteer to help translate bitcoin.org. This blog post recognizes these people and thanks them for their efforts.

blog: Add 'Recognizing Recent Efforts By Volunteer Contributors on the Translation Team

---

docs/managing-wallets.md

This PR is to remove the optional wallet security audit criterion.   Note that we still have a required criterion that specifies
* Sufficient users and/or developers feedback can be found without concerning issues, or independent security audit(s) is available
such that a security audit is an acceptable alternative to sufficient feedback.
Over the last few years, our optional criteria section has served as a place to list criteria that we think are good ideas and we want to convey that to the community and encourage developers to consider them, while not precluding any wallets that have not yet met the optional criteria.
I believe that security audit is certainly a good idea, but I don't believe we will be making it a requirement in the foreseeable future.    One reason is because of the …

Remove optional security audit wallet criteria

---

_templates/getting-started.html

This resolves an issue on the [Getting Started](https://bitcoin.org/en/getting-started) page, where the "Read More" link under "Accounting and Taxes" erroneously points to a portion of a subpage on the Bitcoin Wiki about "Setting Prices".
The link has been updated to correctly point to the [tax compliance](https://en.bitcoin.it/wiki/Tax_compliance) page on the Bitcoin Wiki, instead.

getting-started: Update tax compliance link to correct page

---

_templates/exchanges.html

This exchange is suffering delay on withdrawals:
- https://cointimes.com.br/situacao-comeca-a-ficar-desesperadora-para-clientes-da-3xbit/
- https://cointimes.com.br/3xbit-eletropay-perde-investimento-de-r32-milhoes-do-shark-tank/
- https://www.reclameaqui.com.br/empresa/3xbit/
- https://webitcoin.com.br/leasing-da-3xbit-atrasos-e-promessas-20-out/
- https://portaldobitcoin.com/3xbit-atrasa-saques-em-reais-e-em-bitcoin-e-pede-ate-tres-semanas-para-devolver-dinheiro/
It is best to wait until everything returns to normal (if it become the case) to add it again.
It was already removed from:
- https://bitvalor.com/
- https://www.cointradermonitor.com/preco-bitcoin-brasil
and many other sites.

Removing 3xbit Brazilian exchange.

---

_translations/en.yml

This fixes a missing preposition ("with") in one of tool tips in the wallet wizard, and will be merged once tests pass.

translations/en: Fix missing preposition, "with"

---

docs/managing-wallets.md

Resolves #3173 with a clarification that can apply to layer 2 components, such as Lightning Network, as well as clarify how I believe exchange components have been handled for the last few years.  The new clarified wording of the criterion is 
* User has access to private keys for all major components of the wallet

Clarify wallet private key criterion

---

README.md
docs/adding-exchanges.md

Closes #3174 and provides documentation that can be referenced for how to add an exchange, review fee details plus instruction for waiving fee.
Cc: @Cobra-Bitcoin

New documentation for adding exchanges (related: #3174)

---

_templates/bitcoin-paper.html

This resolves a typo [mentioned](https://github.com/wbnns/bitcoinwhitepaper/issues/85#issue-530743956) by a contributor who is doing Persian language translation work, and will be merged once tests pass.
Cc: @ZeeAmini

bitcoin-paper: Fix typo

---

en/bitcoin-core/features/user-interface.md

The original link for mSigna throws a connection error. Perhaps the website's certificate expired?

Update mSigna link

---

_templates/community.html

This drops a couple of sites that have been down and unresponsive for a couple of weeks, now, from the community page, and will be merged once tests pass:
+ [Svenska Bitcoinföreningen](http://www.bitcoinforeningen.se/)
+ [Fundación Bitcoin de Venezuela](https://www.bitcoinvenezuela.org/)
Cc: @khendraw

Drop unresponsive sites from Community page

---

_translations/ar.yml
_translations/bg.yml
_translations/da.yml
_translations/de.yml
_translations/el.yml
_translations/en.yml
_translations/es.yml
_translations/fa.yml
_translations/fr.yml
_translations/hi.yml
_translations/hu.yml
_translations/id.yml
_translations/it.yml
_translations/ja.yml
_translations/ko.yml
_translations/nl.yml
_translations/pl.yml
_translations/pt_BR.yml
_translations/ro.yml
_translations/ru.yml
_translations/sl.yml
_translations/sr.yml
_translations/sv.yml
_translations/tr.yml
_translations/uk.yml
_translations/zh_CN.yml
_translations/zh_TW.yml

When reviewing #3231, we noted that on the [Community page](https://bitcoin.org/en/community) in the `Social Networks` section, the Facebook link points to a [specific page](https://www.facebook.com/bitcoins) that is outdated. This PR updates the section to make each entry uniform and follow the convention of the Twitter link, so that both links point users to a hashtag search, rather than a specific page. 
Unless others object, this is scheduled to be merged on Friday, January 10th.

translations: Update/standardize social media links

---

_templates/exchanges.html

Bitvavo is an Amsterdam based fiat exchange with 2.4m EUR volume today, with 850k on BTC-EUR. All 50+ assets have both a EUR and BTC pair.
Please check https://coinmarketcap.com/exchanges/bitvavo/ or https://account.bitvavo.com/markets/BTC-EUR for more information.

Add Bitvavo to European exchanges

---

_data/devdocs/en/guides/transactions.md

Bitcoin transactions locked to a block height `H` become valid at height
`H` and can be relayed, but they may only be included in a block of
height `H + 1`.
H/T: Pieter Wuille
Refs:
* https://github.com/bitcoin/bitcoin/blob/v0.19.0.1/src/consensus/tx_verify.cpp#L21L22
* https://bitcoin.stackexchange.com/q/92412/5406

Correct the inclusion height for locktime

---

_wallets/eclairmobile.md

This resolves #3239. The developer, [ACINQ](https://play.google.com/store/apps/developer?id=ACINQ), has two versions of Eclair Mobile on Google Play:
+ [Eclair Mobile v0.4.9](https://play.google.com/store/apps/details?id=fr.acinq.eclair.wallet.mainnet2)
+ [Eclair Mobile v0.4.9 Testnet](https://play.google.com/store/apps/details?id=fr.acinq.eclair.wallet)
This PR changes the URL that the install button on the [Eclair Mobile wallet page](https://bitcoin.org/en/wallets/mobile/android/eclairmobile/?step=5&platform=android) is pointing to, from the testnet version to the mainnet version.
Cc: @crwatkins, @dpad85
Related: [Eclair Mobile v0.4.9 on GitHub](https://github.com/ACINQ/eclair-mobile/releases/tag/v0.4.9-MAINNET)

eclairmobile: Point to mainnet version

---

_templates/exchanges.html

This adds Bitvavo (recently reviewed and added under Europe in #3183), to the Netherlands - the country where they are based - so that Dutch users know that they have a local/domestic option.
Cc: @VoxPopulus

exchanges: Add Bitvavo to Netherlands

---

_templates/exchanges.html

During a recent review of exchanges listed on the site, we noted that OmniTrade (listed under Brazil) did not respond to a test inquiry we sent to their support team, posing as a new customer with questions about deposits and withdrawals (they still have yet to reply). In addition to this, we've noted that the volume being self-reported on their site is very low and non-existent in some cases. We are also noting some inconsistencies in their order book:
For example, they're currently reporting approximately .54 BTC in trade volume over the past 24H for BTC/BRL (low volume) but showing a 0.00% change over the same time period alongside it.
Based on the above, we recommend removing OmniTrade at this time.
Cc: @khendraw

exchanges: Drop OmniTrade

---

Gemfile
Gemfile.lock

This upgrades the redcloth gem to >= 4.3.0 to patch against an XSS
vulnerability and will be merged once tests pass.

Gemfile: Upgrade RedCloth

---

.gitignore

We will be updating Jekyll soon, and the newer version utilizes a
caching API. This adds its cache folder (`.jekyll-cache/`), which is set
aside for site builds, to the `.gitignore` to ensure that it isn't
getting tracked along with  repository changes and accidentally included
in people's pull requests.

gitignore: Adds '.jekyll-cache/'

---

_templates/exchanges.html

This removes BL3P from the European section of the Exchanges page. They are only allowing people to sign up who have invite codes, which we've confirmed during review, and also with their team. This would preclude the majority of people discovering the exchange via bitcoin.org from transacting with them.

exchanges: Drop BL3P

---

_data/devdocs/en/references/p2p_networking.md

Headers in a `headers` message are fixed 81 bytes (80 bytes block header + 1 byte tx count equal to zero).

Small P2P Network document fix

---

_events.yml

This removes a couple of postponed events as a result of corona virus (new dates TBD), and will be merged once tests pass. We'll continue to check other events on a regular basis and remove those that are canceled or postponed.
Closes #3290.

Remove postponed events from Events page

---

_templates/resources.html

This drops a link to the 'Bitcoin Volatility Index' from the Resources page and will be merged once tests pass. The existing link is redirecting to another site that doesn't appear to have a web server configured, resulting in an error message.

resources: Drop 'Bitcoin Volatility Index'

---

_events.yml

This changes the date of the Portland Bitcoin Conference (#3234), which has been rescheduled due to coronavirus, and will be merged once tests pass.

events: Reschedule date, 'Portland Bitcoin Conference'

---

js/main.js

This fixes #3303 and will be merged once tests pass.

main: Replace paywalled BitAverage API

---

_events.yml

This drops the Portland Bitcoin Conference from the events page. We've
noted that their website is down, and is no longer accessible during
successive attempts to reach it, for two weeks, now.

events: Drop 'Portland Bitcoin Conference'

---

.travis.yml
Makefile

This applies a specific version to Rubygems to resolve a deprecation warning that Travis was reporting during builds.
**Before:**
**After:**
The Makefile has also been tweaked to ensure that going forward, builds will fail if any warnings are reported in the log.

travis: Fix deprecation warnings

---

_templates/exchanges.html

This adds Binance's listing to Europe alongside where they were, under the United Kingdom, as per the supported countries mentioned on their website:
https://support.binance.je/hc/en-us/articles/360023983411-Supported-Banks-Jurisdictions
This is scheduled to be merged on Wednesday, May 20th.

exchanges: Add Binance to Europe

---

_config.yml

This updates the block reward from 12.5 to 6.25 in `_config.yml` and
will be merged once tests pass.

config: Update block reward from 12.5 to 6.25

---

_templates/bitcoin-paper.html

This updates the credits for each translator of the Finnish translation
of the Bitcoin paper (similarly to other translations), and will be
merged once tests pass.

bitcoin-paper: Finnish translator credits

---

_templates/bitcoin-paper.html

This updates a few translator credits for two different translations of the Bitcoin paper.
+ Finnish: Removes two redundant translator credits (there was a miscommunication with the submitter regarding who the people who translated it were)
+ Hindi: Updates the link for translator credit, by request of the submitter
This is scheduled to be merged on Monday, June 1st.

Update Bitcoin paper translators

---

_releases/v0.20.0.md
_templates/download.html

Create release page for 0.20.0 Based on bitcoin-core/bitcoincore.org#703.
Can be merged if it passes Travis.

Bitcoin Core 0.20.0

---

_wallets/wasabi.md

By default, Wasabi shows the Bitcoin Core smart fee estimate for transaction fees. However, in the settings, the user can toggle the option to [manually set a custom feerate](https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#how-do-i-set-custom-fee-rate).
I am not sure if I understand it correctly, but I believe that the correct level for this in the score is `checkgoodfeecontrolfull`. If I am mistaken, then please disregard and close the PR. Thank You!

Update Wasabi fee control override

---

_templates/exchanges.html

This removes [Buenbit](https://buenbit.com/index.php), an exchange in Argentina, from the Exchanges page. They're now focused primarily on the exchange of DAI, which is reflected throughout their homepage.
A user visiting the exchange from bitcoin.org would no doubt be confused by this, were they looking to buy and sell bitcoin.
Examples from the homepage:
**1**
**2**
**3**
**4**
We also noted that during a recent check of support team response times for exchanges listed on bitcoin.org, that they still haven't replied to our message:

exchanges: Remove Buenbit

---

_templates/exchanges.html

This removes the Bitex listing under Argentina on the exchanges page and will be merged once tests pass. During a [recent review](https://docs.google.com/spreadsheets/d/1k90K6aCj9MMQZjDoMbQsG5_B7MZ4YHkCg_gmtP1G_ag/edit?usp=sharing) of average customer support response times for the 60+ exchanges listed on the site, Bitex did not reply to multiple inquires from separate email addresses - the earliest of which was sent approximately two weeks ago. We know the inquiries were received because we received auto-generated ticket numbers.
For measure of comparison, the average customer support response time for exchanges listed on the site is 1.32 days.
Cc: @khendraw

exchanges: Remove Bitex

---

_templates/exchanges.html

This removes the Ripio listing under Argentina on the exchanges page and will be merged once tests pass. During a recent review of average customer support response times for the 60+ exchanges listed on the site, Ripio did not reply to multiple inquires from separate email addresses - the earliest of which was sent approximately two weeks ago. We know the inquiries were received because we immediately received auto-generated ticket numbers after the emails were sent.
We contacted Ripio out of band via Twitter this week and were told they would look into the issue. Yesterday, we received a reply to one of our original emails, stating that they have been having problems with their SMS system, and this is why we're having trouble logging in. None of our inquiries were about having trouble …

exchanges: Remove Ripio

---

_templates/exchanges.html

This removes Foxbit, a Brazilian exchange, from the Exchanges page. It was [recently mentioned](https://ourbitcoinnews.com/caixa-economica-closes-accounts-of-at-least-five-bitcoin-companies-in-10-days/) in the news that one of the larger banks in Brazil has begun closing accounts of some of the local exchanges.
Whether related or not, yesterday, we received an automated email from Foxbit that account holders must log in to the site within the next two weeks (by June 30th), and provide updated account holder information, or the account will be permanently closed:
The email states that should an account holder not update their information by the 30th, and would like to use the platform after that date, that they will need to create a new account. This is concerning because this will …

exchanges: Remove Foxbit

---

_templates/exchanges.html

Hello maintainers. I'd like to humbly propose adding our company River Financial (https://river.com) as a US Bitcoin exchange. We offer people the ability to buy, sell and manage their Bitcoin holdings. River users can withdraw and deposit Bitcoin from/to their account on-chain or via the Lightning Network.
We are committed to always providing the latest Bitcoin functionality to our clients. You can see here (https://bitcoinops.org/en/compatibility/) that we are fully segwit compatible. We will also be rolling out some new features over the coming months for hardware wallet integration making it easy for people to move their coins from River to their self custody.
I understand that there is a review process and I will reach out to the appropriate email regarding that.

Add River Financial as an exchange in the US

---

_sass/_wallet-selector.scss

FIX Design issue for 'choose-your-wallet' page on mobile

---

docs/managing-wallets.md

Closes #3111
There have been concerns about the issue that our existing optional HSTS preload criterion relies on a list maintained by a third party (Google) outside of our control.  This PR attempts to mitigate that by specifying which HSTS directives are to be used to qualify for HSTS preload by all major browsers and does not require the Google preload list.
As an aside, I believe this is an important conceptual difference, but I will admit in practice it does not make much difference because we already retain complete control of revisions to the criterion.  I don't see this being significantly different, in terms of control, from referencing a BIP or an IETF informational RFC.
This PR requires the preload directives for new listings, but not does not require existing listing to be …

HSTS preload for wallets

---

_translations/en.yml

Resolves #3136 
This change is to replace the confusing term "Neutral" with a more accurate "Not applicable".  This only affects hardware wallets.
@nvk

Change Neutral wallet score label to Not applicable

---

_templates/exchanges.html

Requesting to add our Middle Eastern platform, [Rain.bh](https://rain.bh).
Rain officially launched and received licensure from the Central Bank of Bahrain on [July 31, 2019](https://www.coindesk.com/crypto-exchange-rain-raises-from-bitmex-opens-trading-in-middle-east). We natively support: BHD, KWD, AED, SAR, OMR, and USD. Open for signup from all jurisdictions besides US and sanctioned countries.
Follow up to https://github.com/bitcoin-dot-org/bitcoin.org/pull/3108 with conflicts resolved

Add Rain.bh to exchanges

---

_sass/_wallets.scss

Minor design issue with the OS name dropdown on wallet pages (mobile only) - fix #3427

FIX OS name line-height on wallet pages (#3427)

---

_wallets/electrum.md

Reflecting the lightning support added since Electrum 4.0.0
CC: @ecdsa as the maintainer of `spesmilo/electrum`

Add lightning support to Electrum

---

_posts/2019-09-24-new-design-for-wallet-pages.md
_translations/en.yml
docs/managing-wallets.md

All wallets can receive from bech32 by definition of soft fork
All wallets that can receive to can also send from, so the "send from"
part needs no extra mention.

Feature bech32 is about sending/receiving to, only

---

_templates/exchanges.html

- Added new section for Taiwan
- Added the 2 major Taiwanese exchanges: MaiCoin MAX and BitoPro

Adding list of Taiwanese exchanges

---

css/rtl.scss

- Fix RTL padding for main content
- Add RTL direction for headlines of FAQ content
FAQ page: https://bitcoin.org/he/faq

Update rtl.scss: FAQ direction for RTL languages

---

en/bitcoin-core/features/privacy.md
en/bitcoin-core/features/requirements.md
en/bitcoin-core/features/validation.md

I noticed some broken HTML at https://bitcoin.org/en/bitcoin-core/features/requirements which led me to discover several pages that appear to have had the closing ">" of line break tags moved to a separate line from the "<br"

fix broken line break tags

---

css/rtl.scss

- Fix homepage  buttons direction
- Fix 'wallet-hint' margin and 'tooltip' direction
- Fix 'about-us' timeline

Update rtl.scss: RTL improvements

---

_wallets/electrum.md

Resolves #3488 
Update the transparency score for Windows and Linux build to deterministic.

Update Electrum wallet transparency

---

docs/managing-wallets.md

Resolves #3476 
This clarifies that we expect open source firmware where possible while currently providing a specific exception for firmware running on secure elements that cannot be shared.

Clarify open source firmware for hardware criteria

---

_templates/exchanges.html

[Swan Bitcoin](https://www.swanbitcoin.com/) is bitcoin-only.

Add Swan Bitcoin to US exchanges

---

_templates/exchanges.html

Second biggest exchange in Poland, operate in Bitcoin mainly, regulated in Poland.

Add Bitclude.com into exchanges.html 

---

_translations/en.yml

While viewing `bitcoin.org/en/bitcoin-paper` I stumbled upon two broken links, at the very bottom of the page.
I believe `_translations/en.yml` is the file that is expected to be edited in this case.
I searched through @wbnns 's visible repos for replacement links since the old ones originated from one of his repos, without success, so I settled for links pointing to this repo.
0397df9 Replaces link to now point to [Assisting-with-translations.md](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/assisting-with-translations.md#assisting-with-translations)
f8d0420 Replaces link to now point to [Issue creation](https://github.com/bitcoin-dot-org/Bitcoin.org/issues/new)
Available if I was mistaken in the file needed to be edited and changes being needed.

Broken links to GitHub repo in bitcoin.org/en/bitcoin-paper

---

js/main.js

The link on the donation link that has the URI `bitcoin:<address>` does not update when the QR code is updated. As a result clicking the link will not relay the selected amount to the application that handles it. This PR fixes this.

Donation: Ensure address link has full URI (incl amount)

---

_templates/resources.html

Bitrawr allows users to filter exchanges in their country based on price, fees, features, security, reputation, and more. With over 50k organic users per month, Bitrawr is now one of the first sites that new users see before getting their first bitcoins.

Add Bitrawr to list of exchange resources

---

_translations/en.yml

Military Grade cryptography as a term is problematic as it lacks clear definition today.
Most modern cryptography is 'military grade' and use of cryptography by civilian and military alike is similar and commonplace.
What was once a hip marketing buzzword now looks dated and does not speak to the sheer magnitude of the computational power that secures Bitcoin.
I think bitcoin dot org removing this statement with a more abstract "mathematics and energy", with a quick note on why these two concepts protect Bitcoin would be a good move to deprecate this dated marketing phrase and give the reader a better understanding of the fundamental concepts protecting their money.

Remove "military-grade cryptography" phrase

---

_templates/exchanges.html

Coinext is one of the top Brazilian exchanges.
This is an update to the PR https://github.com/bitcoin-dot-org/Bitcoin.org/pull/2864, which was sent a few months ago. Tell me if you guys need a test account.

Add Coinext, a Brazilian exchange

---

_templates/resources.html

Fix a broken link after some website consolidation. 
node.guide now resolves to bitcoiner.guide/node

Fix broken link

---

_templates/exchanges.html

Remove 'bitcoin only' tag:
- BitQuick: https://bitquick.co/
-  Paxful: https://paxful.com/

Update exchanges: 'bitcoin only' tag

---

_templates/exchanges.html

Bit2C is the only exchange based in Israel and one of the first in the world.
About Bit2c: [https://bit2c.co.il/home/about](https://bit2c.co.il/home/about)
> Bit2C (ביטוסי בע"מ 514879683) was established as a cryptocurrency exchange platform in March 2013 and is one of the first exchanges to be found in the world.
> Bit2C holds a permit (No. 56980) to provide financial services according to the Financial Services Inspection Law (2016) and is pending to receive its permanent license from The Capital Market Authority.

Add bit2c.co.il into exchanges.html

---

_templates/exchanges.html

This PR adds currency.com to the list of Bitcoin Exchanges
Links:
Site functionality: https://currency.com/
Operational processes: https://currency.com/s-center
Rates and fees: https://currency.com/fees-charges
Order book: https://currency.com/tokenized-securities-overview
Policies, terms, and conditions: https://currency.com/agreement
Press and community feedback: https://apps.apple.com/by/app/currency-com-crypto-exchange/id1458917114
Leadership: https://currency.com/about-us
Links were added to the next locations:
Asia: Bahrain, Malaysia, Taiwan, Israel, Kuwait, Oman, South Korea, Saudi Arabia, Singapore, UAE
EU: without specification
Africa: Nigeria, South Africa, Uganda
North America: Mexico
South Africa: Argentina, Chile , Peru, Brazil, Venezuela, Colombia

Add currency.com to list of Bitcoin Exchanges

---

_config.yml
en/full-node.md

The easier it is to run a full node, the more full nodes Bitcoin will have. The more full nodes Bitcoin has, the more people use full nodes, and the fewer people use custodial solutions, making bitcoin more decentralized. By noting how only 5GB of disk space is required, we can improve the decentralization of bitcoin.
This page is the page most people land on. The wording on this page talks about "minimums". While there is a separate page on the actual minimum requirements, most people will not see it, they will see this 350GB requirement and think "better use a custodial solution."

Make minimum requirements accurate to improve decentralization

---

_templates/bitcoin-paper.html

Hi.
As discussed in the actual whitepaper (Romanian translation) related pull request ( https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3630 ) I've made the update in the actual web page's template too.
Thank you.

Updated whitepaper Romanian translator name in web page to match the pdf

---

_releases/v0.21.1.md

Add bitcoin 0.21.1 release (Taproot release), so we can get this on several projects (eg. Umbrel or any other projects using the same underlying frameworks as Umbrel)

Add bitcoin 0.21.1

---

_translations/en.yml

This is a follow up to #3624. (In summary, a pruned node is a fully verifying node, capable of strengthening Bitcoin in the hands of economic actors and away from custodians that operate full nodes. It uses significantly less disk space, which encourages more people to run full nodes.)
> You should make sure that you have enough bandwidth and storage for the full block chain size (over 350GB).
This pull request changes it to the following:
> You should make sure that you have enough bandwidth and storage for the block chain size (7GB).
- Changes "full block chain size" to "block chain size"
- Changes "over 350GB" to "7GB"
This only changes the English version.
There is an open draft pull request to my version to add translations: crazypython/Bitcoin.org#1
Translators are welcome to …

Fix download page to use pruned size

---

_wallets/bitbox.md

The BitBox02 has had multisig support for quite a while.
https://hwi.readthedocs.io/en/latest/devices/index.html#support-matrix
https://github.com/digitalbitbox/bitbox02-firmware/pulls?q=is%3Apr+multisig+is%3Aclosed

_wallets/bitbox: add multisig to the features list

---

en/full-node.md

As of 22.0, the max number of outgoing connections is 10.
C.f. https://github.com/bitcoin-dot-org/Bitcoin.org/issues/3852 for details.

Max outbound connections is now 10

---

_templates/exchanges.html

Update exchanges page. See title.

Rename coinmana.net to coinmana.com. Remove obsolete binance.je (Jersey)

---

_templates/exchanges.html

Dear Bitcoin.org team,
We would like to submit a request to be listed in the Peer-to-Peer (P2P) section on https://bitcoin.org/en/exchanges#international
Regards,
Hodl Hodl team

Add Hodl Hodl to the list of Peer-to-Peer (P2P) exchanges

---

_templates/bitcoin-paper.html

While we will upload the Slovenian translation of the whitepaper very soon, there's a conflict with a typo in the Slovak whitepaper version title that I've fixed with this pull request. 
**Explanation**
_Slovenčina_ is the Slovak language. In comparison, _Slovenščina_ is the Slovene language. Two different countries and nations.
Can you see the difference where one "š" is missing?
🇸🇰 (sk) Slovak language = Slovenčina
🇸🇮 (si) Slovenian language = Slovenščina
Country flags are also very similar

Slovencina is not Slovenščina

---

_templates/exchanges.html

The links to the Binance exchange in <exchanges.html> are outdated and not valid anymore. This PR fixes that.

Update <exchanges.html> with valid link to Binance

---

_templates/exchanges.html

Hi, I'm a developer at Bitcoin Well.
We've been in operation since 2013. 
In 2021 we listed on the TSXV as the world’s first publicly traded non-custodial bitcoin company.
Is there any chance we could add a non-custodial tag similar to the `Bitcoin Only` tag?
We have also recently entered the U.S. market. Would we be able to list under both Canada and the United States?
More info: [https://bitcoinwell.com/about-bitcoin-well/](https://bitcoinwell.com/about-bitcoin-well/)

Update exchanges.html adding BitcoinWell.com

---

_templates/exchanges.html

Hi again, I appreciate you merging [my previous PR](https://github.com/bitcoin-dot-org/Bitcoin.org/pull/4132) from December. 
The diff looks larger on this PR. I cleaned up some alignment issues caused by a mix of spaces and tabs.
Summary:
- Cleaned up several tab+space issues to fix alignment
- Updated Bitcoin Well listing w/ 'Bitcoin Only' tag
- Added Bitcoin Well listing to the United States section

Cleanup exchanges.html + updated Bitcoin Well listing

---

_translations/en.yml

This PR is to add a new option for the hardware wallet environment score.  This score is meant for hardware wallets that allow the user to provide their own hardware.  It is important to note:
* This PR alone makes no visible change to the site.  This update is for use on future wallet listings.
* Historically the community has been hesitant to add new scoring that might only apply to only one or two wallets.
* Currently there are two open PRs for wallets ([SeedSigner](https://github.com/bitcoin-dot-org/Bitcoin.org/pull/4179) and [AirGap Vault](https://github.com/bitcoin-dot-org/Bitcoin.org/pull/4019)) that this could apply to, and other wallets exist that could qualify (e.g. Specter-DIY, Krux).
* The icon that will appear to users in the comparison charts for this new score will be …

Add environment score for DIY hardware wallets

---

_wallets/bitbox.md

https://github.com/digitalbitbox/bitbox02-firmware/ is now at https://github.com/BitBoxSwiss/bitbox02-firmware/.

bitbox02: fix source code URL

---

docs/managing-wallets.md

There has been an optional criterion for many years on hardware wallet listings to avoid attacks by preventing the downgrading of firmware to a potentially vulnerable version.   Some currently listed hardware wallets simply prevent downgrades while others allow the capability of the current firmware to prohibit the installation of specified versions.
I propose making this a required criterion.   The original criterion was slightly reworded to take into account both implementations described above.

Prevent firmware downgrades

---

_templates/resources.html

Updated the broken link for the Coldcard guide from "https://mattodell.keybase.pub/coldcard.html" to "https://coldcard.com/docs/quick/" in the Resources page. This change ensures that users are directed to the correct and functional URL for the Coldcard guide. 🚀

Fix broken link to Coldcard guide in resources page

---

_templates/exchanges.html

https://cryptobuyer.com/ was acquired by https://coinapult.com/acquired/ and seems to no longer be operational.
Remove reference and link from https://bitcoin.org/en/exchanges#p2p

Remove Cryptobuyer from exchanges page

---

_templates/exchanges.html

Within https://bitcoin.org/en/exchanges#africa >> BuyCoins Nigeria >>  https://buycoins.africa/ >> "This service has been suspended by its owner." >> 503 Error
Removing exchange and associated URL from page.

Remove BuyCoins Africa from exchanges page

---

_templates/resources.html

Removed the broken link to TradeBlock (http://tradeblock.com) from the Resources page as the website is currently unreachable and there are reports that TradeBlock has been shut down by the Digital Currency Group (DCG) due to regulatory and economic conditions.
Updated the Resources page by removing TradeBlock and link from list entirely to reflect this change.
Alternatively, we can add this source for on-chain data and charts, such as The Block's On-Chain Data page (https://www.theblock.co/data/on-chain-metrics/bitcoin).
This ensures users have access to reliable and current sources for Bitcoin data and statistics. 🚀

Remove TradeBlock & broken link from resource link

---

_templates/resources.html

This PR removes the link to the "Evolution of Bitcoin" documentary from the _templates/resources.html file.
**Reason for removal:**
The content is no longer available on YouTube.
**Changes:**
Removed the block containing the link:
<a href="https://www.youtube.com/watch?v=HUpGHOLkoXs">Evolution of Bitcoin</a>

Remove unavailable 'Evolution of Bitcoin' link from resources

---

en/full-node.md

**Description correction:**
Corrected `using the the install` to `using the install`
Corrected `missing file missing and install` to `missing file and install`

fix: typos in documentation files

---

_releases/v27.1.md
_releases/v27.2.md
_releases/v28.0.md

Together with #4349 this brings the Bitcoin Core releases on the site up to date.

Add Bitcoin Core 27.1 27.2 and 28.0 release

---

_releases/v28.1.md
_templates/download.html

This PR adds Bitcoin Core 28.1 release:
https://bitcoincore.org/en/2025/01/09/release-28.1/

Add Bitcoin Core 28.1 release

---

_wallets/wasabi.md

Wasabi is currently only recommended for advanced users. Providing Wasabi Wallet as a recommendation for new users makes sense now since the release of Wasabi 2.0 earlier in June 2022. The on-boarding user experience has been simplified to abstract away complexity from the end user, without compromising on privacy. A total redesign of the client was released allowing less technical users to use a bitcoin wallet that has privacy by default. More can be done to make it even simpler, of course, but it is a step in the right direction for mainstream bitcoin privacy.

Add Wasabi Wallet for New Users

---

docs/setting-up-your-environment.md

Added extra info regarding compilation error for ruby 2.5.8 when setting up your environment. The error occurred with the latest version of Linux Mint (22.1), but I found others complaining about this issue on Ubuntu too.

More info on setting up env instructions
