_templates/community.html, _templates/resources.html
I propose to add two websites
* [CryptoFR](http://www.cryptofr.com/):  A growing French forum, created by [some disappointed](https://bitcointalk.org/index.php?topic=682126.0) of bitcointalk.
* [GoBitcoin.io](http://gobitcoin.io/en/): A multilingual Bitcoin Converter. I hesitated few times to propose this one because I administer it, I'm therefore not the best to judge.
=> Links: Add two websites

_build/txpreview/addlang.rb, _build/txpreview/ansi2html, _build/update_site.sh, _build/update_stats.sh, _build/update_torrent.sh, _build/update_txpreview.sh
(As suggested in #773)
These scripts are already in use in the build machines, which are now shared between two administrator (David and me), so it is becoming more important to make sure everyone keeps the same version.
Edit: These scripts wouldn't be auto-updated via the repository.
=> Add script used to build and update website

_events.yml
[Events page](http://insidebitcoins.com/hong-kong/2015)
=> Insidebitcoins.com add new event (Hong Kong)

_templates/community.html
Suggested by @martijnw (thanks!)
In the absence of critical feedback, this pull will be merged on Thursday.
=> Community: Add Bitcoin Embasy Amsterdam

_layouts/base.html, _less/screen.less, _plugins/alerts.rb
Live preview: http://bitcointest3.us.to/en/
As suggested in #934, this makes the full alert banners clickable.
In the absence of critical feedback, this pull request will be merged on July 5th.
=> Make full alert banners clickable

_events.yml
=> Add Event; avalBit: Pay Paella with bitcoin

_events.yml
For more information, contact: @martijnw
=> Add Bitcoin Thrill Day to Events; Resolve #960.

en/full-node.md
Upgraded all instances of 0.10 to 0.11. Confirmed instructions required no other changes.
=> Upgrade full-node instructions from 0.10.0 to 0.11.0

_includes/references.md
One line fix, but I noticed this URL was broken.
=> Fixed broken url to script.h

_events.yml
[Inside Bitcoins San Diego](http://insidebitcoins.com/san-diego/2015)
=> Add Inside Bitcoins San Diego to event page

_includes/ref/bitcoin-core/rpcs/rpcs/lockunspent.md
unlock (boolean, required) Whether to unlock (true) or lock (false) the specified transactions
=> Correct true/false for Lock or Unlock

_templates/community.html
added [French reddit](http://www.reddit.com/r/BitcoinFrance/), [facebook group](https://www.facebook.com/groups/BitcoinFrance/) and irc [#cryptofr](https://webchat.freenode.net/?channels=cryptofr) (way more active people there than in #bitcoin-fr)
would it be possible to add the major meetups too ?
=> Adding French communities links

_events.yml
Updated the events page with several new upcoming events. Also fixed a few inconsistencies in some existing events.
=> Update Events Page

_events.yml, _templates/about-us.html
I changed my GitHub ID a couple of weeks ago.
=> Update Will's GitHub ID

_templates/choose-your-wallet.html
Per discussion with dev in https://github.com/bitcoin-dot-org/bitcoin.org/issues/1040#issuecomment-137864985
=> Wallets: Remove Hive iOS

_alerts/2015-10-12-upnp-vulnerability.md
Please feel free to merge this pull request at any time (signed with either David or Wladimir PGP key)
=> Update UPnP alert message with links to releases

_templates/about-us.html
This updates the about page with a change to my user name.
=> _templates/about-us.html: Update GitHub user name

en/full-node.md
Preview: http://dg0.dtrt.org/en/full-node#configuration-tuning
Two commits:
1. A quick introduction to configuring Bitcoin Core.
2. @jonasschnelli's bandwidth reduction instructions from https://github.com/bitcoin/bitcoin/pull/6987
Jonas: I set the second commit's author information to your own, since those are your instructions with just minor formatting changes.  Please let me know if that's a problem.
=> Full node guide: describe reducing bandwidth options

en/bitcoin-core/capacity-increases-faq.md, en/bitcoin-core/capacity-increases.md, en/bitcoin-core/index.md
Preview: http://dg0.dtrt.org/en/bitcoin-core/capacity-increases-faq
This adds a FAQ to accompany yesterday's roadmap statement.
=> [Bitcoin Core] Add capacity increses FAQ

_events.yml
=> Update _events.yml with correct San Fran event date

_templates/about-us.html
Hello, just wanted to move myself to inactive status to open up
opportunities for others, as I've not been present to actively manage
translations or other tasks.
=> about: Move to Inactive

_includes/layout/base/footer-js.html, _less/screen.less, js/main.js
=> Add ad infrastructure

_includes/templates/index.html
=> romanian voice-over video

_releases/v0.12.1.md
=> Bitcoin Core 0.12.1

_includes/devdoc/example_p2p_networking.md
Add in commas and comments to match other example send() calls
=> Example formating

_templates/about-us.html
Small update to the contributor page as I have not been active since a while.
=> Move Saivann Carignan into inactive contributors

_templates/choose-your-wallet.html
Documentation on 2FA: http://docs.electrum.org/en/latest/2fa.html
=> Updating properties of Electrum Wallet to indicate 2FA support.

_releases/v0.13.1.md
Can be merged if it passes travis
=> Bitcoin Core 0.13.1

_alerts/2016-10-28-alert-retirement.md, _alerts/2016-11-01-alert-retirement.md
This is the post for the prefinal alert.
@gmaxwell @Cobra-Bitcoin @laanwj
=> Prefinal alert take 2

_templates/about-us.html
I updated my GitHub username and just wanted to fix the GitHub link.
=> about: Updating my username/fixing link

_releases/v0.13.2.md
Can be merged when Travis passes
=> Bitcoin Core 0.13.2

_templates/community.html
This resolves an issue where-in the countries were not lining up correctly, causing the layout to look messed up on the [Community](https://bitcoin.org/en/community) page.
Unless others object, this will be merged on Wednesday, January 4th.
=> community: Fix misalignment issue in country listing

_templates/choose-your-wallet.html
Official announcement of new homepage: https://blog.trezor.io/new-trezor-io-55cf687c88d5#.w9cflkgsr
=> Update homepage of TREZOR wallet

_alerts/2016-11-01-alert-retirement.md
Update the alert retirement alert page with information about the final alert being broadcast
See also: https://github.com/bitcoin/bitcoin/pull/9594
=> Update alert retirement with final alert

_templates/exchanges.html
This fixes an issue with the display of the Indonesian flag as noted in #1496.
// Fixes #1496
=> exchanges: Fix Indonesian flag

_data/glossary/en/soft-fork.yaml
As suggested in #1431 
Not happy with the description but better than the old one and options are quite limited with 255 chars.
=> New softfork description

_templates/community.html
Added most popular german and russian bitcoin boards. Also removed outdated Romanian board.
=> Community sites update

_templates/exchanges.html
Adding The Rock Trading (https://therocktrading.com)
=> Add The Rock Trading

_templates/exchanges.html
=> added CoinCorner

_templates/exchanges.html
=> Updated exchanges.html

_templates/resources.html
Added an up to date list of companies accepting Bitcoin as payment.
=> Updated resources.html

_config.yml
#1450 needs to be merged first
=> Add REST calls, new OP codes and BIPs to dev search

_releases/v0.14.0.md
Add release announcement for 0.14.0.
Should be merge-able as soon as Travis passes.
=> Bitcoin Core 0.14.0

en/full-node.md
I'm looking for appropriate places to link to my config generator; I think anyone who is reading this part of the documentation would be interested in it.
=> Link to config generator

_releases/v0.14.1.md
Should be ready for merge if it passes travis
=> Bitcoin Core 0.14.1

_templates/choose-your-wallet.html
Armory 0.96.0 allows users to set RBF on a transaction and to subsequently bump the fee of said transaction.
=> Upgrade Armory fee control from pass to good

_includes/devdoc/bitcoin-core/rpcs/rpcs/addwitnessaddress.md
Changes:
* "mainet" => "mainnet"
* "redeemscript" => "redeem script"
* Added links to related SegWit BIPs
=> Minor improvements to devdoc: AddWitnessAddress

_templates/exchanges.html
Add "Bits of Gold" Israeli bitcoin change to exchanges page
=> Add Israeli bitcoin change Bits of Gold

_templates/exchanges.html
Added my Australian Exchange Hardblock.net. We have been operating for over three years. Contact me if more info needed.
=> Add HardBlock exchange

_sass/screen.scss
Resolves #1172.
Example:
Bitcoin Address for Bounty: 1LGpP35BthtsjemE9hLL7YbT1jeu8vug8w
=> Better table formatting on small screen devices

_templates/choose-your-wallet.html, _translations/en.yml
The reasons for this change are outlined here: https://btcontract.com/#trusted-node
=> Update Simple Bitcoin Wallet description and validation type

_alerts/2017-07-12-potential-split.md
This adds one more small note to the end of the alert about continuing
to monitor the post for updates, in addition to news sources.
Unless others object, this will be merged on Friday, July 14th.
=> potential-split: Add note about monitoring alert

docs/assisting-with-translations.md
It took me a while to understand those commands.
After I successfully did, I thought it makes sense to update these instructions with comments.
=> Updates instructions of setting up Transifex

_events.yml
This PR adds a couple new upcoming events to the Events page and will be merged once tests pass.
=> Add new events

_templates/resources.html, _translations/en.yml
As per our discussion @wbnns I have added bitcoinprojects.net as a directories link.
Thanks a lot,
James
=> added bitcoinprojects.net to directories

_templates/development.html, _templates/support-bitcoin.html, _translations/en.yml
I am still confused about the translation process. I removed the _walletmultibithd_ string from the en.yml file. Do I need to push this on Transifex too or is this done automatically or periodically by the maintainer?
=> Remaining multibit mentions removed

Makefile, _includes/devdoc/bitcoin-core/rpcs/quick-reference.md, _includes/devdoc/bitcoin-core/rpcs/rpcs/getbalance.md, _includes/devdoc/example_transactions.md, _includes/devdoc/guide_block_chain.md, en/developer-reference.md
=> Devdoc clean up

_autocrossref.yaml, _includes/devdoc/ref_p2p_networking.md, _includes/references.md
Added dates and version 70011.
=> Protocol versions update

_templates/development.html
Added a few full implementations and changed links to the actively used repository.
=> Dev Projects links updated

en/full-node.md
Adds a short section on upgrading Bitcoin Core.
=> Add instructions for upgrading Bitcoin Core

_translations/en.yml
- Fixed BitGive url
- Add Core project as press contact
- Removed unused string (domain doesn't exist any more)
=> Fixed BitGive url

_includes/devdoc/bitcoin-core/rpcs/rpcs/getblock.md
Reference https://github.com/bitcoin/bitcoin/blob/master/src/rpc/blockchain.cpp#L725
=> add verbosity option:2

_alerts/2017-10-09-segwit2x-safety.md
A lot of people are wondering if their coins are safe on a trezor wallet. Pavol and Marek handled the Bcash fork very well and have been strong opponents of Segwit2X. So I think it is safe to say that Trezor can be trusted regarding the fork.
=> Recommend TREZOR

js/main.js
Fixes an issue with not displaying wallet score on tap/click.
Closes #1844.
Bounty can be sent to:
1Nw9hecGRFXRh8kQ437NxycH5AaYXXsc23
=> Fixes the issue with not displaying wallet score on tap/click. Closes #1844

_includes/devdoc/guide_mining.md
remove 'the the' and replace with 'the '
=> Correct typo

_releases/v0.15.1.md
=> Bitcoin Core 0.15.1

_templates/exchanges.html
Automatic exchange. Multinational, but I personally live in the UAE. Strongly No2X (listed here: http://nob2x.org/). Thank you.
=> Add Karsha Exchange

_templates/community.html
Removed "Bitcoin Alliance of India", it no longer exist
=> Removed "Bitcoin Alliance of India", it no longer exist

_includes/devdoc/guide_transactions.md
Fixes issue #1792 
13pskXn8eJhb3byvL6ehGvovKDaNqL1P8s
=> Update developer guide with Segwit Activation details.

en/full-node.md
Just a WAG, but likely sufficient for now.
=> Added suggested IO speeds for storage.

_templates/developer-documentation.html
This PR fixes links on `/en/developer-documentation`
=> Fixes links on developer-documentation.html page

_includes/templates/index.html, _translations/en.yml
These descriptions of transaction features are somewhat open to interpretation; it would probably be best not to oversell Bitcoin given the current state of the network.
It wasn't clear to me if this is the correct way to update the "master" translation; I poked around in Transfinex and didn't see an obvious way to make similar suggestions, but I've never used Transfinex before.
=> update network descriptions to be more accurate

_posts/2018-01-28-vote-on-the-new-site-design.md
This PR updates the text on the recent blog post letting people know that voting has ended (so they don't try to click the link and vote - it will no longer work). This will be merged once tests pass.
The winner was Version 3. :)
=> post: Update design vote post with result

_releases/v0.16.0.md
Can be merged if Travis passes
=> Bitcoin Core 0.16.0

_data/devdocs/en/guides/payment_processing.md
=> linking bitcoin wiki / units

_data/devdocs/en/bitcoin-core/rpcs/rpcs/getmempoolancestors.md, _data/devdocs/en/bitcoin-core/rpcs/rpcs/getmempooldescendants.md, _data/devdocs/en/bitcoin-core/rpcs/rpcs/getmempoolentry.md
Fixed merge for PRs: #2028 #2029 #2030
=> Fix input parameter from Address to TXID for getmempool[entry][descedants][ancestors] 

en/full-node.md
This fixes #1913 and will be merged once test pass.
=> full-node: Change Ubuntu version to 16.04

en/full-node.md
This fixes #1970 and will be merged once test pass.
=> full-node: Add sync requirement for using BitNodes

_templates/exchanges.html
This resolves #2047 and will be merged once tests pass.
=> Remove dead links to exchanges

docs/contributing-to-developer-documentation.md
The resolves #2057 and will be merged once tests pass.
=> contributing: Fix broken link

_translations/en.yml
This resolves #2107 and will be merged once tests pass.
=> en: Remove broken link to Lighthouse app

_templates/exchanges.html
Hi, Added Coinmama as International Exchange
=> Add Coinmama to International exchanges

_templates/exchanges.html
This supersedes PR #2296, resolving its merge conflict, and will be
merged once tests pass.
=> exchanges: Add OmniTrade

_data/devdocs/en/guides/block_chain.md
This resolves #2214 and will be merged once tests pass.
=> block_chain: Fix typographical error in docs

_translations/ar.yml, _translations/bg.yml, _translations/da.yml, _translations/de.yml, _translations/el.yml, _translations/en.yml, _translations/es.yml, _translations/fa.yml, _translations/fr.yml, _translations/hi.yml, _translations/hu.yml, _translations/id.yml, _translations/it.yml, _translations/ja.yml, _translations/ko.yml, _translations/nl.yml, _translations/pl.yml, _translations/pt_BR.yml, _translations/ro.yml, _translations/ru.yml, _translations/sl.yml, _translations/sv.yml, _translations/tr.yml, _translations/uk.yml, _translations/zh_CN.yml, _translations/zh_TW.yml
This resolves #2429 and will be merged once tests pass.
=> _translations: Fix link pointing to broken Wiki page

_data/devdocs/en/examples/transactions.md
value is required field for offline signing
=> add value to offline signing

_releases/v0.16.1.md
TODO:
[x] Upload binaries
[x] Fill in torrent URL
Can be merged once Travis passes.
=> Bitcoin Core 0.16.1

_data/devdocs/en/guides/transactions.md
Hi! I fixed the issue #1924. Does the bounty still count? :-)
My address is 3GsjjePXvMqoTYucCXgFbm4uRnt7NdAj59
=> Clarification for P2SH in the developer guide

en/full-node.md
Hi! I made a (possible) fix for the issue #1633. Not really confident with my wording and style though...
=> Add IBD section in the full node guide

_templates/exchanges.html
[Cryptoradar](https://cryptoradar.co) is a tool which compares the prices, fees and features of different exchanges. 
It could help users to filter this long list of exchanges based on their individual criteria.
=> Add Cryptoradar to exchange list

en/rss/blog.xml
This fixes https://github.com/bitcoin-dot-org/bitcoin.org/issues/2512.
=> Fixes RSS XML Bug

_layouts/about-sidebar.html, _layouts/development-sidebar.html, _layouts/sidebar.html, _templates/developer-documentation.html, _templates/events.html, _templates/vocabulary.html, en/alerts.html, en/blog.html
jQuery was sometimes loading twice, which caused the old version (injected with the qr version), to be void.
I fixed this by injecting the qr code script again and by removing some duplicate jQuery imports.
Fixes: #2532 
Address: 3BPucBK5Y6ybvouBGw7husQfwk86BRkSQE
=> Fixed qrcode JavaScript error

_releases/v0.16.2.md
=> Bitcoin Core 0.16.2

_templates/exchanges.html
Had a mistake the last time, fixed now. Thanks!
=> Added Argentinian exchange

_data/devdocs/en/bitcoin-core/rpcs/rpcs/estimatepriority.md
PR  for adding deprecated to estimatefee #2219
=> Fix for #2219: Add deprecated to estimatefee and estimatedpriority

_config.yml
=> _config: Add redirects; languages without buy page

_data/devdocs/en/guides/block_chain.md
change rawtransaction to raw transaction
=> change rawtransaction to raw transaction

_config.yml, _templates/about-us.html, _translations/sr.yml
This updates the Serbian translation on the site and will be merged once tests pass. It also adds Pavel Nedved as the coordinator for the Serbian translation on the About Us page (thanks Pavel!).
=> Update Serbian Translation

_sass/screen.scss
This fixes #2619 and will be merged once tests pass.
=> screen: Fix dotted path on Getting Started page

_templates/exchanges.html
Hello, we are sending request for adding Kriptomat.io to list of european exchanges
=> Kriptomat.io added to exchanges list

_templates/exchanges.html
Add new Brazillian exchange to trade Bitcoins with security.
https://brasilbitcoin.com.br/
=> Add new Brazillian Brasil Bitcoin Exchange

_releases/v0.16.3.md
[Context.](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2664#commitcomment-30573777)
Cc: @nimchak @laanwj
=> _releases: Fix date

_wallets/greenaddress.md
GreenAddress android clients should use Greenbits instead.
=> Remove deprecated GreeenAddress android app

_releases/v0.17.0.md
Can be merged when it passes travis.
=> Bitcoin Core 0.17.0

_data/devdocs/en/bitcoin-core/rpcs/rpcs/getwalletinfo.md
Updates the documentation for `getwalletinfo`.
=> Update the documentation for getwalletinfo

_includes/layout/base/footer-menu.html
=> Fix privacy policy strings

en/full-node.md
=> full-node: Add clarification to instrux for version number

docs/managing-wallets.md
Update the HSTS preload list URL for Chrome.
=> Update HSTS preload list URL

_includes/layout/base-core/footer-license.html, _includes/layout/base/footer-license.html, _includes/layout/base/footer-menu.html, _translations/en.yml
=> Add missing translation strings

_config.yml
=> _config: Update datadir size in gigabytes

_templates/resources.html
=> resources: Drop news section

_translations/de.yml
This updates the site's German translation with all of the latest strings and is scheduled to be merged on Monday, October 22nd.
=> _translations/de: Update German Translation

_config.yml, _templates/development.html, _translations/nl.yml
This updates the site's Dutch translation with all of the latest strings and is scheduled to be merged on Monday, October 22nd.
=> _translations/nl: Update Dutch Translation

_releases/v0.17.0.1.md
(can be merged once it passes travis)
=> Bitcoin Core 0.17.0.1

_templates/exchanges.html
Closes #2750.
This is scheduled to be merged on Friday, November 23rd.
=> exchanges: Drop Bitwage

_config.yml, _templates/development.html, _translations/pt_BR.yml
This updates the site's Portuguese (Brasil) translation with all of the latest strings and is scheduled to be merged on Friday, December 7th.
=> _translations: Update Portuguese (BR) Translation

_data/devdocs/en/guides/contracts.md
Extend CoinJoin explanation with currently operational implementations and their descriptions.  
Resolves: https://github.com/bitcoin-dot-org/bitcoin.org/issues/2785
=> Improve CoinJoin Description

_releases/v0.17.1.md
Add Bitcoin Core 0.17.1 release
=> Bitcoin Core 0.17.1

LICENSE
Updates the year in the license to the current year.
=> Update year to 2019

_data/devdocs/en/bitcoin-core/api-intro.md, _data/devdocs/en/bitcoin-core/rpcs/intro.md, _data/devdocs/en/bitcoin-core/rpcs/rpcs/ping.md, _data/devdocs/en/examples/transactions.md
This pull request contains a few small fixes to the markup to make processing a bit more explicit or clean.
=> Markdown fixes

_templates/exchanges.html
=> exchanges: Change name to 'iCE3X'

_templates/exchanges.html
We are one of the exchanges in Japan. If you have any questions please let me know.
Thanks in advanced.
=> Add bitbank to Japan exchanges list

_config.yml, _includes/layout/base/footer-menu.html, _includes/layout/base/head-menu.html, _templates/getting-started.html
This resolves #2816 and will be merged once tests pass.
Cc: @Stadicus
=> Update conditionals and relative links pointing to translated pages

_events.yml
When merged; possibly closes #2820 #2825
=> Removes past events from the Events page and adds two new ones 

_wallets/keepkey.md
... since v4.0.3
See: https://github.com/keepkey/keepkey-firmware/issues/25#issuecomment-370549896
Closes #2836
=> KeepKey has deterministic builds

_templates/resources.html
bitaps.com  - Addresses distribution chart, last blocks, mempool stats and fee distribution chart, nodes map, PoW stats ...
=> added bitaps.com to Charts and Statistics

_includes/layout/base/wallets-filter.html
Resolves #2844 and will be merged once tests pass. Thank you @ap4y for helping prepare the patch.
Cc: @crwatkins
=> wallets-filter: Remove conditional to hide current wallet from selector

js/events.js
Closes #2879 and will be merged once tests pass.
Cc: @annetdeboer
=> js/events: Use https for tileLayer

_events.yml
https://www.bitcoin2019conference.com/
=> Add event listing for Bitcoin 2019 conference

_data/devdocs/en/references/p2p_networking.md, _includes/references.md
For reference: https://github.com/bitcoin/bitcoin/blob/fa2510d5c1cdf9c2cd5cc9887302ced4378c7202/src/protocol.h#L246-L279
=> Update node service identifier flags

_templates/exchanges.html
Adding one of Canada's top exchanges, Bitbuy to the exchanges section for Canada
=> Add Bitbuy to Exchanges

_releases/v0.18.0.md
Can be merged if it passes travis
=> Bitcoin Core 0.18.0

_templates/community.html
add ChainNode.com to the "Bitcoin community" page
=> add ChainNode.com to the "Bitcoin community" page

en/full-node.md
=> Broken link - init scripts

_includes/references.md
Remove redundant trailing double quote
=> Fix quoting

_config.yml, _templates/development.html, _translations/hu.yml
This updates the site's Hungarian translation with all of the latest strings and is scheduled to be merged on Friday, May 24th.
=> translations: Update Hungarian Translation

_templates/exchanges.html
Coinsmart had fixed css issues!
=> Include new canadian exchange!

_wallets/bither.md
Refs: https://github.com/bitcoin-dot-org/bitcoin.org/issues/3043
=> Update Bither to indicate HD wallet is now the default

_data/devdocs/en/bitcoin-core/api-intro.md, _data/devdocs/en/bitcoin-core/rest/quick-reference.md, _data/devdocs/en/bitcoin-core/rest/requests/get_block-notxdetails.md, _data/devdocs/en/bitcoin-core/rest/requests/get_block.md, _data/devdocs/en/bitcoin-core/rest/requests/get_blockhashbyheight.md, _data/devdocs/en/bitcoin-core/rest/requests/get_headers.md, _includes/references.md
I'm not sure if formatting is correct but content should be :)
=> Add GET BlockHashByHeight

docs/managing-wallets.md
Let's give submitters another hint so they can help us better.  No new policy here that I know of, just doc update.
=> Add guidance on trademark capitalization

_releases/v0.18.1.md
Add bitcoin core 0.18.1
Can be merged if it passes travis
=> Bitcoin Core 0.18.1

_data/glossary/en/block-size-limit.yaml
=> Glossary: update block size limit

_includes/layout/base/helper-step-2.html
Resolves #3092 and will be merged once tests pass.
Cc: @Cobra-Bitcoin @alexcherman
=> helper-step-2: Drop overridden heading

_posts/2019-09-24-new-design-for-wallet-pages.md
Now that the newly designed wallet pages have soft-launched and have been live for a little bit, this PR adds a new blog post announcing the change. Thank you to the community as well as everyone that contributed to the project.
Cc: @crwatkins @Cobra-Bitcoin @natiwa @alexcherman @maxwellmons
=> blog: Add 'A New Design for Wallet Pages'

_templates/exchanges.html
Update changed domain for HardBlock hardblock.net to hardblock.com.au
=> Update exchanges.html 

_events.yml
Removed past events; added future events. Once merged; closes #3155 and #3137
=> Events housekeeping

_events.yml
This adds 3 new events to the Events page and will be merged once tests pass:
+ #3158
+ #3167
+ #3179
Cc: @khendraw
=> Update Events Pages

_releases/v0.19.0.1.md
Binaries have been uploaded, this can be merged when it passes Travis.
=> Bitcoin Core 0.19.0.1

en/bitcoin-core/features/user-interface.md
Reverts bitcoin-dot-org/bitcoin.org#3206
=> Revert "Update mSigna link"

.travis.yml, Makefile
This updates the Travis configuration to resolve an issue with bundler not successfully installing in the build environment, causing tests to fail across various PRs:
=> travis: Add additional parameters

_wallets/mycelium.md
Resolves #3221 
Update Mycelium score to reflect deterministic builds.
Thanks @giszmo @schildbach.
=> Update Mycelium transparency score

LICENSE
This updates the year in the `LICENSE` file to 2020 and will be merged once tests pass.
Happy New Year!
=> LICENSE: Update year to 2020

_templates/exchanges.html
This closes #3220, removes Hodl Hodl and is scheduled to be merged on Wednesday, February 19th.
=> exchanges: Remove Hodl Hodl

_includes/layout/base/helper-step-4.html, _includes/layout/base/wallets-selector.html, _posts/2019-09-24-new-design-for-wallet-pages.md, _translations/en.yml, _translations/ja.yml, _wallets/wasabi.md
Closes #3276 and will be merged once tests pass.
=> wallets: Drop mixing/shuffling filter

_releases/v0.19.1.md
=> Bitcoin Core 0.19.1

_templates/about-us.html
Removes theymos from list of co-owners.
=> Removes theymos from list of co-owners

_translations/ja.yml
This updates the site's Japanese translation and is scheduled to be merged on Friday, May 8th.
=> Update Japanese Translation

_config.yml, _translations/ar.yml, _translations/bg.yml, _translations/da.yml, _translations/el.yml, _translations/es.yml, _translations/fa.yml, _translations/fr.yml, _translations/he.yml, _translations/hi.yml, _translations/ko.yml, _translations/pl.yml, _translations/ro.yml, _translations/ru.yml, _translations/sl.yml, _translations/sv.yml, _translations/tr.yml, _translations/uk.yml, _translations/zh_TW.yml
=> Drop redirects for localized pages

_layouts/wallet-container.html, _sass/_wallets.scss, css/rtl.scss
This PR contains RTL formatting improvements to ensure that languages like Arabic and Hebrew display properly when rendered across the site.
Cc: @alexcherman, @ZeevBB
=> RTL improvements

css/rtl.scss
=> Update rtl.scss: menu issues for RTL languages

css/rtl.scss
=> Update rtl.scss: footer issue for RTL languages

_wallets/wasabi.md
=> Add hardware wallet support for Wasabi

_wallets/mycelium.md
Mycelium supports Trezor, KeepKey and Ledger.
@Giszmo OK?
=> Add hardware wallet support for Mycelium

css/rtl.scss
=> Update rtl.scss: margin issues for RTL languages

_events.yml
=> Add new event - Issue #3406

_templates/exchanges.html
=> Add OKCoin to list of exchanges

_templates/exchanges.html
=> Update exchanges to include Bitaroo (Australian Bitcoin Only Exchange)

_layouts/wallet-container.html
=> Add 'features-title' translaction string

_includes/layout/base/footer-menu.html, _includes/layout/base/head-menu.html
Added links of missing translated pages to both header and footer menus.
=> Fixing some links

_templates/exchanges.html
Added Mine Digital exchange to Australian Exchange list
=> Updated exchanges.html to include Mine Digital

_templates/bitcoin-paper.html
I've just changed my personal website url.
Sorry for the inconveniences.
=> Modify link

_templates/resources.html
I've been maintaining this directory of resources for several years and curating over a thousand links to resources of all types.
I think it's generally considered to be the most comprehensive guide to resources for the ecosystem; hopefully it's worthy of being linked to from bitcoin.org
=> link to lopp.net bitcoin resources list

_templates/development.html
BTCPay Server is a free and open-source cryptocurrency payment processor which allows you to receive payments in Bitcoin directly, with no fees, transaction cost or a middleman.
BTCPay Server is a non-custodial invoicing system which eliminates the involvement of a third-party. Payments with BTCPay Server go directly to your wallet, which increases the privacy and security. Your private keys are never uploaded to the server. There is no address re-use, since each invoice generates a new address deriving from your xpubkey.
=> Add 'BTCPay Server' to free software projects

_translations/pt_BR.yml
Updates the Portuguese (Brazil) translations to the latest versions
=> Update Portuguese (Brazil) translations

css/rtl.scss
Closes #3522
URL: https://bitcoin.org/he/exchanges
| Before | After | 
|--|--|
| ![image](https://user-images.githubusercontent.com/8020386/101588113-977f5100-3a20-11eb-9e88-e0588078cf33.png) | ![image](https://user-images.githubusercontent.com/8020386/101588017-63a42b80-3a20-11eb-84ad-c85506bb9622.png) |
=> Fix RTL issues on 'exchanges' page

en/bitcoin-core/features/requirements.md
=> Add Windows 10 to compatible OSs

_templates/exchanges.html
Add Crypto.com into exchanges page #international section
=> Add Crypto.com into exchanges.html

_templates/exchanges.html
Adds Norwegian Block Exchange to list of exchanges, in a new "Norway" sub-section
See https://nbx.com
=> Add Norwegian Block Exchange to exchange list

en/full-node.md
=> fix for #3528

_layouts/wallet-container.html
Apple is [now](https://developer.apple.com/news/?id=06142019a) using apps.apple.com for downloads.
Also, cleaned up some trailing whitespace.
=> Add new Apple download domain

_wallets/unstoppable.md
=> Correct unstoppable wallet compat tag

_templates/resources.html
=> add statoshi.info to resources#charts

_templates/resources.html
=> add guides panel to resources

en/full-node.md
=> en/full-node.md: add how to video

_templates/exchanges.html
Please accept this pull request to add NDAX to bitcoin.org
Thank you
=> Add NDAX to Canadian Bitcoin Exchanges

_templates/exchanges.html
Adding Coinmama to UAE, UK and US as discussed
=> Adding Coinmama to UAE, UK and US

_templates/exchanges.html
I added Coinmama back in without the submodules that caused the last PR to revert.
=> Added Coinmama without submodules

_includes/layout/base/helper-step-2.html
=> Fixes data-text user experience values to use liquid translate tags

_includes/references.md, _templates/resources.html
@crwatkins This is the new PR adding mempool.space and removing `[block170]` in two commits.
=> Add mempool.space

en/full-node.md
change "each time your reboot your computer" to "each time you reboot your computer"
=> Fixed Typo

_releases/v0.10.0.md, _releases/v0.14.0.md, _releases/v0.14.1.md, _releases/v0.14.2.md, _releases/v0.15.0.1.md, _releases/v0.15.0.md, _releases/v0.15.1.md, _releases/v0.16.0.md, _releases/v0.16.1.md, _releases/v0.16.2.md, _releases/v0.9.0.md, _releases/v0.9.1.md, _releases/v0.9.2.1.md, _releases/v0.9.2.md, _releases/v0.9.3.md
=> Improve UX around removed release binaries

_templates/exchanges.html
Site functionality: 
https://www.bitfinex.com/about/
Operational processes:
https://support.bitfinex.com/hc/en-us
Rates and fees
https://www.bitfinex.com/fees  
Order book
https://trading.bitfinex.com/trading
Policies, terms and conditions
https://www.bitfinex.com/legal/exchange/terms
Press and community feedback
https://twitter.com/bitfinex
Leadership
https://www.bitfinex.com/about#leadership
=> Update  exchanges.html  to include Bitfinex.com

_templates/exchanges.html
Added Coincheck website as a Japanese exchange. 
Coincheck is known as one of the largest crypto exchange in Japan.
=> Add Coincheck on exchange.html

_templates/exchanges.html
Added paybtc to Australian exchanges list
=> Updated exchange.html to include paybtc

_templates/bitcoin-paper.html
=> Remove redundant spanish translation

_templates/resources.html
iamsatoshi.com has been down since February 2022, unsure if it will come back.
=> Replacing dead domain with webarchive version

_templates/bitcoin-paper.html
Hello, this is a Marathi translation of the Bitcoin whitepaper. 
The PDF for this can be found on github https://github.com/shivajiambedkar/bitcoin-marathi/blob/main/bitcoin_mr.pdf (I didn't know how or where to put the file in the repo)
=> Update bitcoin-paper.html with मराठी (Marathi) translation

_templates/resources.html
Seems to be back up, reverting #3902.
=> Reverting #3902 - iamsatoshi.com is back on

_wallets/electrum.md
Electrum-android is built reproducibly and supports 2fa and multisig
=> update features and transparency for electrum-android

_templates/exchanges.html
Removed Walltime (terminated operations last year) Added major brazilian exchanges like Bitypreço, Ripio, Foxbit and others
=> Update exchanges.html adding new exchanges and removing broken links

_templates/exchanges.html
This PR is adding [Uphold](https://uphold.com/en-eu) to the exchanges list.
=> Add Uphold exchange

_wallets/bitcoincore.md
=> Add hardware and multisig features to Bitcoin Core Wallet

quality-assurance/schemas/wallets.yaml
This updates the schema for the change made in #4194. 
This new score is referenced in #4179.
=> Update schema for DIY hardware wallets
